# Aula 04 - Avaliação de Estratégias de Chunking com LangChain

## Teste 1 - Chunk fixo de 200 caracteres, sem overlap

In [1]:
from langchain_text_splitters import CharacterTextSplitter
from pathlib import Path

c:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
arquivo = Path("markdown/bioetica_e_ia.md")

texto = arquivo.read_text(encoding="utf-8")

print("Quantidade de caracteres:", len(texto))

Quantidade de caracteres: 44347

In [3]:
splitter = CharacterTextSplitter(
    separator="",
    chunk_size=200,
    chunk_overlap=0
)

In [4]:
chunks = splitter.split_text(texto)

print("Quantidade de chunks:", len(chunks))

Quantidade de chunks: 222

In [5]:
for i, chunk in enumerate(chunks[:5], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("Tamanho:", len(chunk))

============================================================
CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medic
Tamanho: 200
============================================================
CHUNK 2
ina da Universidade do Porto, Porto, Portugal.

## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de t
Tamanho: 200
============================================================
CHUNK 3
riagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidad
Tamanho: 200
============================================================
CHUNK 4
os especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à au
Tamanho: 200
============================================================
CHUNK 5
tonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este artigo revis
Tamanho: 200

In [6]:
tamanhos = [len(chunk) for chunk in chunks]

print("Número total de chunks:", len(chunks))
print("Tamanho médio:", sum(tamanhos) / len(tamanhos))
print("Tamanho mínimo:", min(tamanhos))
print("Tamanho máximo:", max(tamanhos))
print("Overlap:", 0)

Número total de chunks: 222
Tamanho médio: 199.4189189189189
Tamanho mínimo: 146
Tamanho máximo: 200
Overlap: 0

In [7]:
splitter_teste_2 = CharacterTextSplitter(
    separator="",
    chunk_size=500,
    chunk_overlap=0
)

chunks_teste_2 = splitter_teste_2.split_text(texto)

tamanhos_teste_2 = [len(chunk) for chunk in chunks_teste_2]

print("Número total de chunks:", len(chunks_teste_2))
print("Tamanho médio:", sum(tamanhos_teste_2) / len(tamanhos_teste_2))
print("Tamanho mínimo:", min(tamanhos_teste_2))
print("Tamanho máximo:", max(tamanhos_teste_2))
print("Overlap:", 0)

Número total de chunks: 89
Tamanho médio: 497.92134831460675
Tamanho mínimo: 347
Tamanho máximo: 500
Overlap: 0

In [8]:
for i, chunk in enumerate(chunks_teste_2[:3], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("Tamanho:", len(chunk))

============================================================
CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoc
Tamanho: 500
============================================================
CHUNK 2
es, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este artigo revis
Tamanho: 500
============================================================
CHUNK 3
a a literatura sobre os principais dilemas éticos da aplicação da inteli -gência artificial na prática médica e avalia em que medida os princípios hipocráticos podem ser preser -vados ou adaptados diante das transformações tecnológicas, a fim de contribuir para o debate sobre os rumos éticos da medicina contemporânea em um cenário de crescente automação.

Palavras-chave: Bioética. Inteligência artificial. Ética médica. Autonomia pessoal.

## Resumen

## Entre el algoritmo y el Juramento Hipocrát
Tamanho: 500

### Observação do Teste 2

O chunking fixo de 500 caracteres reduziu a quantidade de chunks em relação
ao teste de 200 caracteres, porém ainda apresentou fragmentação de palavras,
sentenças e parágrafos.

Isso ocorre porque a divisão considera apenas a quantidade de caracteres,
sem levar em conta a estrutura semântica do texto.

In [9]:
tamanhos_teste_2 = [len(chunk) for chunk in chunks_teste_2]

print("Número total de chunks:", len(chunks_teste_2))
print("Tamanho médio:", sum(tamanhos_teste_2) / len(tamanhos_teste_2))
print("Tamanho mínimo:", min(tamanhos_teste_2))
print("Tamanho máximo:", max(tamanhos_teste_2))
print("Overlap:", 0)

Número total de chunks: 89
Tamanho médio: 497.92134831460675
Tamanho mínimo: 347
Tamanho máximo: 500
Overlap: 0

In [10]:
splitter_teste_3 = CharacterTextSplitter(
    separator="",
    chunk_size=1000,
    chunk_overlap=0
)

chunks_teste_3 = splitter_teste_3.split_text(texto)

tamanhos_teste_3 = [len(chunk) for chunk in chunks_teste_3]

print("Número total de chunks:", len(chunks_teste_3))
print("Tamanho médio:", sum(tamanhos_teste_3) / len(tamanhos_teste_3))
print("Tamanho mínimo:", min(tamanhos_teste_3))
print("Tamanho máximo:", max(tamanhos_teste_3))
print("Overlap:", 0)

Número total de chunks: 45
Tamanho médio: 985.1333333333333
Tamanho mínimo: 347
Tamanho máximo: 1000
Overlap: 0

In [11]:
for i, chunk in enumerate(chunks_teste_3[:3], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("Tamanho:", len(chunk))

============================================================
CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este artigo revis
Tamanho: 1000
============================================================
CHUNK 2
a a literatura sobre os principais dilemas éticos da aplicação da inteli -gência artificial na prática médica e avalia em que medida os princípios hipocráticos podem ser preser -vados ou adaptados diante das transformações tecnológicas, a fim de contribuir para o debate sobre os rumos éticos da medicina contemporânea em um cenário de crescente automação.

Palavras-chave: Bioética. Inteligência artificial. Ética médica. Autonomia pessoal.

## Resumen

## Entre el algoritmo y el Juramento Hipocrático: bioética en la era de la inteligencia artificial

El avance de la inteligencia artificial ha transformado profundamente la práctica médica. Desde sistemas de apoyo a la decisión clínica hasta algoritmos de triaje y diagnóstico, la inteligencia artificial ha demostrado potencial para diagnósticos precoces, terapias personalizadas, optimización de recursos, reducción de errores y ampliación del acceso a cuidados especializados. No obstante, esta revolución tecnológica impone desafíos éticos s
Tamanho: 1000
============================================================
CHUNK 3
ignificativos a los principios clásicos de la bioética, tales como la beneficencia, la no maleficencia, la confidencialidad y el respeto a la autonomía del paciente, consagrados desde el Juramento Hipocrático. La incorporación de la inteligencia artificial en la medicina suscita tensiones entre la eficiencia automatizada y los valores humanos. Este artículo revisa la literatura sobre los principales dilemas éticos de la aplicación de la inteligencia artificial en la práctica médica y evalúa en qué medida los principios hipocráticos pueden preservarse o adaptarse ante las transformaciones tecnológicas, con el fin de contribuir al debate sobre los rumbos éticos de la medicina contemporánea en un escenario de creciente automatización.

Palabras clave: Bioética. Inteligencia artificial. Ética médica. Autonomía personal.

## Abstract

## Between the algorithm and the Hippocratic Oath: bioethics in the age of artificial intelligence

The advancement of artificial intelligence has profoundly
Tamanho: 999

### Observação do Teste 3

O aumento do tamanho para 1000 caracteres permitiu que cada chunk carregasse
mais contexto em comparação aos testes anteriores. Entretanto, a divisão fixa
por caracteres ainda provocou cortes no meio de palavras, frases e estruturas
do documento.

Isso mostra que apenas aumentar o `chunk_size` não garante preservação
semântica do conteúdo.

In [12]:
tamanhos_teste_3 = [len(chunk) for chunk in chunks_teste_3]

print("Número total de chunks:", len(chunks_teste_3))
print("Tamanho médio:", sum(tamanhos_teste_3) / len(tamanhos_teste_3))
print("Tamanho mínimo:", min(tamanhos_teste_3))
print("Tamanho máximo:", max(tamanhos_teste_3))
print("Overlap:", 0)

Número total de chunks: 45
Tamanho médio: 985.1333333333333
Tamanho mínimo: 347
Tamanho máximo: 1000
Overlap: 0

In [13]:
splitter_teste_4 = CharacterTextSplitter(
    separator="",
    chunk_size=2000,
    chunk_overlap=0
)

chunks_teste_4 = splitter_teste_4.split_text(texto)

tamanhos_teste_4 = [len(chunk) for chunk in chunks_teste_4]

print("Número total de chunks:", len(chunks_teste_4))
print("Tamanho médio:", sum(tamanhos_teste_4) / len(tamanhos_teste_4))
print("Tamanho mínimo:", min(tamanhos_teste_4))
print("Tamanho máximo:", max(tamanhos_teste_4))
print("Overlap:", 0)

Número total de chunks: 23
Tamanho médio: 1927.8695652173913
Tamanho mínimo: 347
Tamanho máximo: 2000
Overlap: 0

In [14]:
for i, chunk in enumerate(chunks_teste_4[:3], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("Tamanho:", len(chunk))

============================================================
CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este artigo revisa a literatura sobre os principais dilemas éticos da aplicação da inteli -gência artificial na prática médica e avalia em que medida os princípios hipocráticos podem ser preser -vados ou adaptados diante das transformações tecnológicas, a fim de contribuir para o debate sobre os rumos éticos da medicina contemporânea em um cenário de crescente automação.

Palavras-chave: Bioética. Inteligência artificial. Ética médica. Autonomia pessoal.

## Resumen

## Entre el algoritmo y el Juramento Hipocrático: bioética en la era de la inteligencia artificial

El avance de la inteligencia artificial ha transformado profundamente la práctica médica. Desde sistemas de apoyo a la decisión clínica hasta algoritmos de triaje y diagnóstico, la inteligencia artificial ha demostrado potencial para diagnósticos precoces, terapias personalizadas, optimización de recursos, reducción de errores y ampliación del acceso a cuidados especializados. No obstante, esta revolución tecnológica impone desafíos éticos s
Tamanho: 2000
============================================================
CHUNK 2
ignificativos a los principios clásicos de la bioética, tales como la beneficencia, la no maleficencia, la confidencialidad y el respeto a la autonomía del paciente, consagrados desde el Juramento Hipocrático. La incorporación de la inteligencia artificial en la medicina suscita tensiones entre la eficiencia automatizada y los valores humanos. Este artículo revisa la literatura sobre los principales dilemas éticos de la aplicación de la inteligencia artificial en la práctica médica y evalúa en qué medida los principios hipocráticos pueden preservarse o adaptarse ante las transformaciones tecnológicas, con el fin de contribuir al debate sobre los rumbos éticos de la medicina contemporánea en un escenario de creciente automatización.

Palabras clave: Bioética. Inteligencia artificial. Ética médica. Autonomía personal.

## Abstract

## Between the algorithm and the Hippocratic Oath: bioethics in the age of artificial intelligence

The advancement of artificial intelligence has profoundly transformed medical practice. From clinical decisionsupport systems to screening and diagnostic algorithms, artificial intelligence has demonstrated potential for early diagnosis, personalized therapies, resource optimization, error reduction, and expanded access to specialized care. However, this technological revolution imposes significant ethical challenges on the classic principles of bioethics, such as beneficence, non-maleficence, confidentiality, and respect for patient autonomy, enshrined since the Hippocratic Oath. The incorporation of artificial intelligence into medicine raises tensions between automated efficiency and human values. This article reviews the literature on the primary ethical dilemmas of applying artificial intelligence in medical practice and evaluates to what extent Hippocratic principles can be preserved or adapted in the face of technological transformations, aiming to contribute to the debate on the ethical directions of contemporary medicine in a scenari
Tamanho: 2000
============================================================
CHUNK 3
o of increasing automation.

Keywords: Bioethics. Artificial intelligence. Ethics, medical. Personal autonomy.

Declaram não haver conflito de interesse.

A introdução da inteligência artificial (IA) na medicina representa um dos maiores saltos tecno -lógicos da história recente da saúde. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a IA tem demonstrado potencial para diagnósticos  precoces,  terapias  personalizadas, otimização de recursos, redução de erros médicos e ampliação do acesso a cuidados especializados, especialmente em regiões remotas ou com escas -sez de profissionais de saúde qualificados  1,2 . Em áreas como dermatologia, radiologia e cardiologia, algoritmos baseados em deep learning (apren -dizado  profundo)  já  demonstram  desempenho comparável, ou mesmo superior, ao de especialis -tas humanos em tarefas específicas 3 .

No entanto, a rápida expansão e incorporação da IA à prática clínica não ocorre sem desafios. A  adoção  acelerada  dessas  tecnologias  suscita preocupações éticas significativas, especialmente no que diz respeito aos princípios fundamentais da bioética. Desde seus primórdios, a medicina tem sido regida por princípios éticos que visam à proteção e ao bem-estar do paciente. O Juramento de Hipócrates, datado do século V a.C., consagrou valores  fundamentais  como  beneficência,  não maleficência, confidencialidade e respeito à auto -nomia do doente - pilares da bioética ainda hoje 4 . Tais valores foram reforçados no século XX por documentos como o Código de Nüremberg e  a Declaração de Helsinki , que consolidaram as bases para a ética em pesquisa e prática médica 3 .

Contudo, o advento da IA na medicina introduz novos e complexos desafios éticos que tensionam esses princípios. Entre os dilemas que emergem estão  a  opacidade  e  a  não  explicabilidade  dos algoritmos - os chamados black boxes -, que difi -cultam a compreensão e a validação das decisões automatizadas por parte de médicos e paciente
Tamanho: 2000

### Observação do Teste 4

Com chunks de 2000 caracteres, cada trecho passou a concentrar uma quantidade
maior de contexto em comparação aos testes anteriores.

Entretanto, a estratégia de divisão fixa por caracteres continuou provocando
cortes no meio de palavras, frases e estruturas do documento. Portanto,
aumentar o tamanho do chunk melhora a quantidade de contexto disponível,
mas não resolve o problema da fragmentação semântica.

In [15]:
tamanhos_teste_4 = [len(chunk) for chunk in chunks_teste_4]

print("Número total de chunks:", len(chunks_teste_4))
print("Tamanho médio:", sum(tamanhos_teste_4) / len(tamanhos_teste_4))
print("Tamanho mínimo:", min(tamanhos_teste_4))
print("Tamanho máximo:", max(tamanhos_teste_4))
print("Overlap:", 0)

Número total de chunks: 23
Tamanho médio: 1927.8695652173913
Tamanho mínimo: 347
Tamanho máximo: 2000
Overlap: 0

In [16]:
splitter_teste_5 = CharacterTextSplitter(
    separator="",
    chunk_size=500,
    chunk_overlap=50
)

chunks_teste_5 = splitter_teste_5.split_text(texto)

tamanhos_teste_5 = [len(chunk) for chunk in chunks_teste_5]

print("Número total de chunks:", len(chunks_teste_5))
print("Tamanho médio:", sum(tamanhos_teste_5) / len(tamanhos_teste_5))
print("Tamanho mínimo:", min(tamanhos_teste_5))
print("Tamanho máximo:", max(tamanhos_teste_5))
print("Overlap:", 50)

Número total de chunks: 99
Tamanho médio: 497.1313131313131
Tamanho mínimo: 246
Tamanho máximo: 500
Overlap: 50

In [17]:
print("FINAL DO CHUNK 1:")
print(chunks_teste_5[0][-150:])

print("\n" + "=" * 60)

print("INÍCIO DO CHUNK 2:")
print(chunks_teste_5[1][:150])

FINAL DO CHUNK 1:
temas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoc

============================================================
INÍCIO DO CHUNK 2:
m demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidad

### Observação do Teste 5

O uso de `chunk_overlap = 50` fez com que parte do final de um chunk fosse repetida
no início do chunk seguinte.

Essa sobreposição ajuda a preservar o contexto em regiões de fronteira entre
os chunks, reduzindo o risco de fragmentar completamente uma ideia entre dois
trechos distintos.

Em contrapartida, o overlap gera redundância de conteúdo e tende a aumentar
a quantidade de informação processada e armazenada.

In [18]:
splitter_teste_6 = CharacterTextSplitter(
    separator="",
    chunk_size=500,
    chunk_overlap=200
)

chunks_teste_6 = splitter_teste_6.split_text(texto)

tamanhos_teste_6 = [len(chunk) for chunk in chunks_teste_6]

print("Número total de chunks:", len(chunks_teste_6))
print("Tamanho médio:", sum(tamanhos_teste_6) / len(tamanhos_teste_6))
print("Tamanho mínimo:", min(tamanhos_teste_6))
print("Tamanho máximo:", max(tamanhos_teste_6))
print("Overlap:", 200)

Número total de chunks: 148
Tamanho médio: 497.9054054054054
Tamanho mínimo: 246
Tamanho máximo: 500
Overlap: 200

In [19]:
print("FINAL DO CHUNK 1:")
print(chunks_teste_6[0][-250:])

print("\n" + "=" * 60)

print("INÍCIO DO CHUNK 2:")
print(chunks_teste_6[1][:250])

FINAL DO CHUNK 1:
 Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoc

============================================================
INÍCIO DO CHUNK 2:
ransformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recurso

## Teste 7 - Chunking por Parágrafos

Nesta estratégia, o documento é dividido utilizando as quebras de parágrafo
como separadores, buscando preservar unidades textuais completas e reduzir
cortes arbitrários no conteúdo.

In [20]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter_teste_7 = RecursiveCharacterTextSplitter(
    separators=["\n\n"],
    chunk_size=1000,
    chunk_overlap=0,
    length_function=len
)

chunks_teste_7 = splitter_teste_7.split_text(texto)

print("Número total de chunks:", len(chunks_teste_7))

Número total de chunks: 57

In [21]:
for i, chunk in enumerate(chunks_teste_7[:5], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("\nTamanho:", len(chunk))

============================================================
CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

Tamanho: 257
============================================================
CHUNK 2


O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este artigo revisa a literatura sobre os principais dilemas éticos da aplicação da inteli -gência artificial na prática médica e avalia em que medida os princípios hipocráticos podem ser preser -vados ou adaptados diante das transformações tecnológicas, a fim de contribuir para o debate sobre os rumos éticos da medicina contemporânea em um cenário de crescente automação.

Tamanho: 1099
============================================================
CHUNK 3
Palavras-chave: Bioética. Inteligência artificial. Ética médica. Autonomia pessoal.

## Resumen

## Entre el algoritmo y el Juramento Hipocrático: bioética en la era de la inteligencia artificial

Tamanho: 195
============================================================
CHUNK 4


El avance de la inteligencia artificial ha transformado profundamente la práctica médica. Desde sistemas de apoyo a la decisión clínica hasta algoritmos de triaje y diagnóstico, la inteligencia artificial ha demostrado potencial para diagnósticos precoces, terapias personalizadas, optimización de recursos, reducción de errores y ampliación del acceso a cuidados especializados. No obstante, esta revolución tecnológica impone desafíos éticos significativos a los principios clásicos de la bioética, tales como la beneficencia, la no maleficencia, la confidencialidad y el respeto a la autonomía del paciente, consagrados desde el Juramento Hipocrático. La incorporación de la inteligencia artificial en la medicina suscita tensiones entre la eficiencia automatizada y los valores humanos. Este artículo revisa la literatura sobre los principales dilemas éticos de la aplicación de la inteligencia artificial en la práctica médica y evalúa en qué medida los principios hipocráticos pueden preservarse o adaptarse ante las transformaciones tecnológicas, con el fin de contribuir al debate sobre los rumbos éticos de la medicina contemporánea en un escenario de creciente automatización.

Tamanho: 1188
============================================================
CHUNK 5
Palabras clave: Bioética. Inteligencia artificial. Ética médica. Autonomía personal.

## Abstract

## Between the algorithm and the Hippocratic Oath: bioethics in the age of artificial intelligence

Tamanho: 197

In [22]:
tamanhos_teste_7 = [len(chunk) for chunk in chunks_teste_7]

print("Número total de chunks:", len(chunks_teste_7))
print("Tamanho médio:", round(sum(tamanhos_teste_7) / len(tamanhos_teste_7), 2))
print("Tamanho mínimo:", min(tamanhos_teste_7))
print("Tamanho máximo:", max(tamanhos_teste_7))

Número total de chunks: 57
Tamanho médio: 776.33
Tamanho mínimo: 195
Tamanho máximo: 1360

### Observação do Teste 7

A estratégia baseada em parágrafos preservou melhor as unidades textuais naturais
do documento e evitou cortes arbitrários no meio das palavras.

Entretanto, alguns parágrafos possuem mais de 1000 caracteres, fazendo com que
determinados chunks ultrapassem o valor definido em `chunk_size`.

Esse comportamento ocorre porque, neste experimento, foi utilizado apenas
`\n\n` como separador, priorizando a preservação integral dos parágrafos.

O resultado evidencia um dos trade-offs do chunking estrutural: maior coerência
semântica pode resultar em chunks de tamanhos menos uniformes.

In [23]:
tamanhos_teste_7 = [len(chunk) for chunk in chunks_teste_7]

print("Número total de chunks:", len(chunks_teste_7))
print("Tamanho médio:", round(sum(tamanhos_teste_7) / len(tamanhos_teste_7), 2))
print("Tamanho mínimo:", min(tamanhos_teste_7))
print("Tamanho máximo:", max(tamanhos_teste_7))

Número total de chunks: 57
Tamanho médio: 776.33
Tamanho mínimo: 195
Tamanho máximo: 1360

## Teste 8 - Sentenças agrupadas em 3

Nesta estratégia, o documento é dividido em sentenças e, em seguida,
três sentenças consecutivas são agrupadas em cada chunk.

O objetivo é avaliar se a utilização de sentenças completas preserva
melhor o contexto do que a divisão puramente baseada em caracteres.

In [24]:
!pip install nltk

Requirement already satisfied: nltk in C:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages (3.10.2)
Requirement already satisfied: defusedxml in C:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in C:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in C:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in C:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages (from nltk) (4.70.0)
Requirement already satisfied: colorama in C:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import nltk

nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ResTIC16\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [26]:
from nltk.tokenize import sent_tokenize

sentencas = sent_tokenize(
    texto,
    language="portuguese"
)

print("Número total de sentenças:", len(sentencas))

Número total de sentenças: 256

In [27]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ResTIC16\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ResTIC16\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [28]:
from nltk.tokenize import sent_tokenize

sentencas = sent_tokenize(
    texto,
    language="portuguese"
)

print("Número total de sentenças:", len(sentencas))

Número total de sentenças: 256

In [29]:
chunks_teste_8 = []

for i in range(0, len(sentencas), 3):
    grupo = sentencas[i:i+3]

    chunk = " ".join(grupo)

    chunks_teste_8.append(chunk)

print("Número total de chunks:", len(chunks_teste_8))

Número total de chunks: 86

In [30]:
tamanhos_teste_8 = [len(chunk) for chunk in chunks_teste_8]

print("Número total de chunks:", len(chunks_teste_8))
print("Tamanho médio:", round(sum(tamanhos_teste_8) / len(tamanhos_teste_8), 2))
print("Tamanho mínimo:", min(tamanhos_teste_8))
print("Tamanho máximo:", max(tamanhos_teste_8))

Número total de chunks: 86
Tamanho médio: 513.5
Tamanho mínimo: 56
Tamanho máximo: 1088

In [31]:
for i, chunk in enumerate(chunks_teste_8[:3], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("\nTamanho:", len(chunk))

============================================================
CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal. ## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica.

Tamanho: 342
============================================================
CHUNK 2
De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos.

Tamanho: 638
============================================================
CHUNK 3
Este artigo revisa a literatura sobre os principais dilemas éticos da aplicação da inteli -gência artificial na prática médica e avalia em que medida os princípios hipocráticos podem ser preser -vados ou adaptados diante das transformações tecnológicas, a fim de contribuir para o debate sobre os rumos éticos da medicina contemporânea em um cenário de crescente automação. Palavras-chave: Bioética. Inteligência artificial.

Tamanho: 424

### Observação do Teste 8

O agrupamento de três sentenças por chunk produziu trechos com tamanhos
variáveis, pois o comprimento das sentenças não é uniforme.

Em comparação com o chunking fixo por caracteres, essa estratégia preservou
melhor unidades completas de sentido, reduzindo cortes no meio de palavras e
frases.

Como desvantagem, os chunks ficaram menos uniformes em tamanho, o que pode
impactar custo e consistência no processamento posterior dos embeddings.

In [32]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter_teste_9 = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100,
    separators=[
        "\n\n",
        "\n",
        " ",
        ""
    ],
    length_function=len
)

chunks_teste_9 = splitter_teste_9.split_text(texto)

print("Número total de chunks:", len(chunks_teste_9))

Número total de chunks: 65

In [33]:
for i, chunk in enumerate(chunks_teste_9[:5], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("\nTamanho:", len(chunk))

============================================================
CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

Tamanho: 257
============================================================
CHUNK 2
O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este artigo revisa a literatura sobre os principais dilemas éticos da aplicação da inteli -gência artificial na prática médica e avalia em que medida os princípios hipocráticos podem ser preser -vados ou adaptados diante das transformações tecnológicas, a fim de contribuir

Tamanho: 997
============================================================
CHUNK 3
podem ser preser -vados ou adaptados diante das transformações tecnológicas, a fim de contribuir para o debate sobre os rumos éticos da medicina contemporânea em um cenário de crescente automação.

Tamanho: 196
============================================================
CHUNK 4
Palavras-chave: Bioética. Inteligência artificial. Ética médica. Autonomia pessoal.

## Resumen

## Entre el algoritmo y el Juramento Hipocrático: bioética en la era de la inteligencia artificial

Tamanho: 195
============================================================
CHUNK 5
El avance de la inteligencia artificial ha transformado profundamente la práctica médica. Desde sistemas de apoyo a la decisión clínica hasta algoritmos de triaje y diagnóstico, la inteligencia artificial ha demostrado potencial para diagnósticos precoces, terapias personalizadas, optimización de recursos, reducción de errores y ampliación del acceso a cuidados especializados. No obstante, esta revolución tecnológica impone desafíos éticos significativos a los principios clásicos de la bioética, tales como la beneficencia, la no maleficencia, la confidencialidad y el respeto a la autonomía del paciente, consagrados desde el Juramento Hipocrático. La incorporación de la inteligencia artificial en la medicina suscita tensiones entre la eficiencia automatizada y los valores humanos. Este artículo revisa la literatura sobre los principales dilemas éticos de la aplicación de la inteligencia artificial en la práctica médica y evalúa en qué medida los principios hipocráticos pueden

Tamanho: 989

In [34]:
tamanhos_teste_9 = [len(chunk) for chunk in chunks_teste_9]

print("Número total de chunks:", len(chunks_teste_9))
print("Tamanho médio:", round(sum(tamanhos_teste_9) / len(tamanhos_teste_9), 2))
print("Tamanho mínimo:", min(tamanhos_teste_9))
print("Tamanho máximo:", max(tamanhos_teste_9))
print("Overlap configurado:", 100)

Número total de chunks: 65
Tamanho médio: 695.02
Tamanho mínimo: 102
Tamanho máximo: 999
Overlap configurado: 100

## Teste 10 - Chunking por Estrutura Markdown

Nesta estratégia, o documento é dividido com base nos headings Markdown,
buscando preservar a organização semântica das seções e subseções.

Também são mantidos, sempre que possível, metadados relacionados ao heading
e à seção de origem de cada chunk.

In [35]:
from langchain_text_splitters import MarkdownHeaderTextSplitter

In [36]:
headers_to_split_on = [
    ("#", "titulo_nivel_1"),
    ("##", "titulo_nivel_2"),
    ("###", "titulo_nivel_3"),
]

In [37]:
splitter_teste_10 = MarkdownHeaderTextSplitter(
    headers_to_split_on=headers_to_split_on
)

In [38]:
chunks_teste_10 = splitter_teste_10.split_text(texto)

print("Número total de chunks:", len(chunks_teste_10))

Número total de chunks: 19

In [39]:
for i, chunk in enumerate(chunks_teste_10[:5], start=1):
    print("=" * 70)
    print(f"CHUNK {i}")
    
    print("\nMETADADOS:")
    print(chunk.metadata)
    
    print("\nCONTEÚDO:")
    print(chunk.page_content)
    
    print("\nTamanho:", len(chunk.page_content))

======================================================================
CHUNK 1

METADADOS:
{}

CONTEÚDO:
273
<!-- image -->

Tamanho: 20
======================================================================
CHUNK 2

METADADOS:
{'titulo_nivel_2': 'Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial'}

CONTEÚDO:
Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1
1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

Tamanho: 132
======================================================================
CHUNK 3

METADADOS:
{'titulo_nivel_2': 'Resumo'}

CONTEÚDO:
O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este artigo revisa a literatura sobre os principais dilemas éticos da aplicação da inteli -gência artificial na prática médica e avalia em que medida os princípios hipocráticos podem ser preser -vados ou adaptados diante das transformações tecnológicas, a fim de contribuir para o debate sobre os rumos éticos da medicina contemporânea em um cenário de crescente automação.
Palavras-chave: Bioética. Inteligência artificial. Ética médica. Autonomia pessoal.

Tamanho: 1183
======================================================================
CHUNK 4

METADADOS:
{'titulo_nivel_2': 'Entre el algoritmo y el Juramento Hipocrático: bioética en la era de la inteligencia artificial'}

CONTEÚDO:
El avance de la inteligencia artificial ha transformado profundamente la práctica médica. Desde sistemas de apoyo a la decisión clínica hasta algoritmos de triaje y diagnóstico, la inteligencia artificial ha demostrado potencial para diagnósticos precoces, terapias personalizadas, optimización de recursos, reducción de errores y ampliación del acceso a cuidados especializados. No obstante, esta revolución tecnológica impone desafíos éticos significativos a los principios clásicos de la bioética, tales como la beneficencia, la no maleficencia, la confidencialidad y el respeto a la autonomía del paciente, consagrados desde el Juramento Hipocrático. La incorporación de la inteligencia artificial en la medicina suscita tensiones entre la eficiencia automatizada y los valores humanos. Este artículo revisa la literatura sobre los principales dilemas éticos de la aplicación de la inteligencia artificial en la práctica médica y evalúa en qué medida los principios hipocráticos pueden preservarse o adaptarse ante las transformaciones tecnológicas, con el fin de contribuir al debate sobre los rumbos éticos de la medicina contemporánea en un escenario de creciente automatización.
Palabras clave: Bioética. Inteligencia artificial. Ética médica. Autonomía personal.

Tamanho: 1273
======================================================================
CHUNK 5

METADADOS:
{'titulo_nivel_2': 'Between the algorithm and the Hippocratic Oath: bioethics in the age of artificial intelligence'}

CONTEÚDO:
The advancement of artificial intelligence has profoundly transformed medical practice. From clinical decisionsupport systems to screening and diagnostic algorithms, artificial intelligence has demonstrated potential for early diagnosis, personalized therapies, resource optimization, error reduction, and expanded access to specialized care. However, this technological revolution imposes significant ethical challenges on the classic principles of bioethics, such as beneficence, non-maleficence, confidentiality, and respect for patient autonomy, enshrined since the Hippocratic Oath. The incorporation of artificial intelligence into medicine raises tensions between automated efficiency and human values. This article reviews the literature on the primary ethical dilemmas of applying artificial intelligence in medical practice and evaluates to what extent Hippocratic principles can be preserved or adapted in the face of technological transformations, aiming to contribute to the debate on the ethical directions of contemporary medicine in a scenario of increasing automation.
Keywords: Bioethics. Artificial intelligence. Ethics, medical. Personal autonomy.
Declaram não haver conflito de interesse.
A introdução da inteligência artificial (IA) na medicina representa um dos maiores saltos tecno -lógicos da história recente da saúde. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a IA tem demonstrado potencial para diagnósticos  precoces,  terapias  personalizadas, otimização de recursos, redução de erros médicos e ampliação do acesso a cuidados especializados, especialmente em regiões remotas ou com escas -sez de profissionais de saúde qualificados  1,2 . Em áreas como dermatologia, radiologia e cardiologia, algoritmos baseados em deep learning (apren -dizado  profundo)  já  demonstram  desempenho comparável, ou mesmo superior, ao de especialis -tas humanos em tarefas específicas 3 .
No entanto, a rápida expansão e incorporação da IA à prática clínica não ocorre sem desafios. A  adoção  acelerada  dessas  tecnologias  suscita preocupações éticas significativas, especialmente no que diz respeito aos princípios fundamentais da bioética. Desde seus primórdios, a medicina tem sido regida por princípios éticos que visam à proteção e ao bem-estar do paciente. O Juramento de Hipócrates, datado do século V a.C., consagrou valores  fundamentais  como  beneficência,  não maleficência, confidencialidade e respeito à auto -nomia do doente - pilares da bioética ainda hoje 4 . Tais valores foram reforçados no século XX por documentos como o Código de Nüremberg e  a Declaração de Helsinki , que consolidaram as bases para a ética em pesquisa e prática médica 3 .
Contudo, o advento da IA na medicina introduz novos e complexos desafios éticos que tensionam esses princípios. Entre os dilemas que emergem estão  a  opacidade  e  a  não  explicabilidade  dos algoritmos - os chamados black boxes -, que difi -cultam a compreensão e a validação das decisões automatizadas por parte de médicos e pacientes, e essa falta de transparência algorítmica compro -mete o princípio da autonomia, pois impede o con -sentimento plenamente informado. Além disso, surgem questões sobre a responsabilização por erros clínicos decorrentes de decisões baseadas em IA, com dúvidas sobre se a culpa recai sobre o médico, o programador, a instituição de saúde ou o próprio algoritmo  2,5,6 .
A privacidade e a proteção de dados sensíveis dos pacientes são outros pontos críticos. Como a IA depende de grandes volumes de dados para treinamento e operação, é essencial garantir que o  tratamento  das  informações  esteja  em  con -formidade com legislações e regulamentações, como  a  Lei  14.510/2022,  que  dispõe  sobre  a prestação de serviços de telessaúde 7 , a Lei Geral de Proteção de Dados (LGPD, Lei 13.709/2018)  8 , e a Resolução do Conselho Federal de Medicina (CFM) 2.314/2022, que define e regulamenta a telemedicina como forma de prestação de servi -ços médicos  9 , no Brasil; o General Data Protection Regulation (GDPR)  10  e a Network and Information Systems  (NIS  Directive) 11 ,  na  União  Europeia; o Health Insurance Portability and Accountability Act (HIPAA) 12 e o Health Information Technology for Economic and Clinical Health Act (HITECH) 13 , nos  Estados  Unidos.  A  violação  da  privacidade ou o uso indevido de dados médicos podem ter consequências devastadoras para os pacientes, incluindo discriminação, estigmatização e danos morais e financeiros.
Adicionalmente, há o risco de ampliar desi -gualdades no acesso à saúde. A implantação de soluções baseadas em IA, muitas vezes desen -volvidas em contextos de alta renda, pode não considerar  adequadamente  as  necessidades, idiomas e realidades socioculturais de populações vulneráveis  ou  de  países  em  desenvolvimento. Isso pode acentuar disparidades já existentes no sistema de saúde e comprometer o princípio da justiça distributiva, fundamental para a equidade no cuidado médico 14 .
Também  merece  preocupação  a  possível desumanização na medicina. A relação médico --paciente,  historicamente  centrada  na  escuta, no cuidado e na empatia, pode ser afetada nega -tivamente  se  a  confiança  for  deslocada  para sistemas  automatizados.  O  excesso  de  depen -dência tecnológica pode tornar o atendimento mais impessoal, comprometendo a integralidade do cuidado e a dimensão subjetiva da experiên -cia do adoecimento  15 . A formação médica, nesse cenário, também deve ser repensada, uma vez que habilidades como pensamento crítico, julgamento clínico e sensibilidade ética precisam ser preserva -das e fortalecidas, mesmo em ambiente cada vez mais orientado por dados  16 .
O  descompasso  entre  a  velocidade  da  ino -vação tecnológica e a capacidade de regulação ética e jurídica impõe, portanto, a necessidade urgente  de  revisar  os  fundamentos  bioéticos sob nova perspectiva. Tais questões exigem não apenas análise técnica, mas abordagem bioética rigorosa, que considere o impacto da IA nos valo -res  fundamentais que regem a prática médica. A literatura recente reforça que princípios éticos isolados não são suficientes para garantir a inte -gridade moral das aplicações de IA: é necessário um sistema de governança robusto, transparente, participativo e que envolva múltiplos stakeholders, incluindo médicos, engenheiros, pacientes, juristas e representantes da sociedade civil 17,18 .
Este artigo tem como objetivo revisar a lite -ratura  existente  sobre  os  principais  dilemas éticos  relacionados  à  aplicação  da  inteligência artificial na prática médica, resgatar os princípios hipocráticos e analisar como eles podem (ou não) ser preservados diante das transformações tec -nológicas em curso. Por meio de análise crítica e multidisciplinar, pretende-se contribuir para o debate sobre os rumos éticos da medicina contem -porânea em um cenário de crescente automação.

Tamanho: 6946

In [40]:
tamanhos_teste_10 = [
    len(chunk.page_content)
    for chunk in chunks_teste_10
]

print("Número total de chunks:", len(chunks_teste_10))
print(
    "Tamanho médio:",
    round(
        sum(tamanhos_teste_10) / len(tamanhos_teste_10),
        2
    )
)
print("Tamanho mínimo:", min(tamanhos_teste_10))
print("Tamanho máximo:", max(tamanhos_teste_10))

Número total de chunks: 19
Tamanho médio: 2283.53
Tamanho mínimo: 20
Tamanho máximo: 6946

### Observação do Teste 10

O chunking baseado na estrutura Markdown conseguiu preservar informações
estruturais do documento por meio dos headings e de seus respectivos metadados.

Diferentemente das estratégias baseadas em tamanho fixo, os chunks apresentaram
grande variação de tamanho, pois a divisão foi determinada pela estrutura das
seções do documento.

Essa estratégia apresenta como vantagem a preservação do contexto estrutural e
dos metadados das seções. Entretanto, se uma seção possuir grande quantidade de
conteúdo, o chunk resultante também pode se tornar muito extenso.

Para aplicações de RAG, uma possível estratégia seria combinar a divisão por
headings com uma segunda divisão dos conteúdos muito extensos.

In [41]:
import pandas as pd

resultados_testes = [
    {
        "Teste": 1,
        "Estratégia": "Fixo",
        "Chunk Size": 200,
        "Overlap": 0,
        "Nº Chunks": len(chunks),
        "Média": round(sum(tamanhos) / len(tamanhos), 2),
        "Mínimo": min(tamanhos),
        "Máximo": max(tamanhos)
    },
    {
        "Teste": 2,
        "Estratégia": "Fixo",
        "Chunk Size": 500,
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_2),
        "Média": round(sum(tamanhos_teste_2) / len(tamanhos_teste_2), 2),
        "Mínimo": min(tamanhos_teste_2),
        "Máximo": max(tamanhos_teste_2)
    },
    {
        "Teste": 3,
        "Estratégia": "Fixo",
        "Chunk Size": 1000,
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_3),
        "Média": round(sum(tamanhos_teste_3) / len(tamanhos_teste_3), 2),
        "Mínimo": min(tamanhos_teste_3),
        "Máximo": max(tamanhos_teste_3)
    },
    {
        "Teste": 4,
        "Estratégia": "Fixo",
        "Chunk Size": 2000,
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_4),
        "Média": round(sum(tamanhos_teste_4) / len(tamanhos_teste_4), 2),
        "Mínimo": min(tamanhos_teste_4),
        "Máximo": max(tamanhos_teste_4)
    },
    {
        "Teste": 5,
        "Estratégia": "Fixo + Overlap",
        "Chunk Size": 500,
        "Overlap": 50,
        "Nº Chunks": len(chunks_teste_5),
        "Média": round(sum(tamanhos_teste_5) / len(tamanhos_teste_5), 2),
        "Mínimo": min(tamanhos_teste_5),
        "Máximo": max(tamanhos_teste_5)
    },
    {
        "Teste": 6,
        "Estratégia": "Fixo + Overlap",
        "Chunk Size": 500,
        "Overlap": 200,
        "Nº Chunks": len(chunks_teste_6),
        "Média": round(sum(tamanhos_teste_6) / len(tamanhos_teste_6), 2),
        "Mínimo": min(tamanhos_teste_6),
        "Máximo": max(tamanhos_teste_6)
    },
    {
        "Teste": 7,
        "Estratégia": "Parágrafos",
        "Chunk Size": 1000,
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_7),
        "Média": round(sum(tamanhos_teste_7) / len(tamanhos_teste_7), 2),
        "Mínimo": min(tamanhos_teste_7),
        "Máximo": max(tamanhos_teste_7)
    },
    {
        "Teste": 8,
        "Estratégia": "3 Sentenças",
        "Chunk Size": "-",
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_8),
        "Média": round(sum(tamanhos_teste_8) / len(tamanhos_teste_8), 2),
        "Mínimo": min(tamanhos_teste_8),
        "Máximo": max(tamanhos_teste_8)
    },
    {
        "Teste": 9,
        "Estratégia": "Recursive",
        "Chunk Size": 1000,
        "Overlap": 100,
        "Nº Chunks": len(chunks_teste_9),
        "Média": round(sum(tamanhos_teste_9) / len(tamanhos_teste_9), 2),
        "Mínimo": min(tamanhos_teste_9),
        "Máximo": max(tamanhos_teste_9)
    },
    {
        "Teste": 10,
        "Estratégia": "Markdown",
        "Chunk Size": "-",
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_10),
        "Média": round(sum(tamanhos_teste_10) / len(tamanhos_teste_10), 2),
        "Mínimo": min(tamanhos_teste_10),
        "Máximo": max(tamanhos_teste_10)
    }
]

df_resultados = pd.DataFrame(resultados_testes)

df_resultados

,Teste,Estratégia,Chunk Size,Overlap,Nº Chunks,Média,Mínimo,Máximo
0,1,Fixo,200,0,222,199.42,146,200
1,2,Fixo,500,0,89,497.92,347,500
2,3,Fixo,1000,0,45,985.13,347,1000
3,4,Fixo,2000,0,23,1927.87,347,2000
4,5,Fixo + Overlap,500,50,99,497.13,246,500
5,6,Fixo + Overlap,500,200,148,497.91,246,500
6,7,Parágrafos,1000,0,57,776.33,195,1360
7,8,3 Sentenças,-,0,86,513.50,56,1088
8,9,Recursive,1000,100,65,695.02,102,999
9,10,Markdown,-,0,19,2283.53,20,6946

## Comparação preliminar das estratégias

Os experimentos demonstraram que o tamanho do chunk influencia diretamente
a quantidade de fragmentos gerados. Entre os testes de tamanho fixo sem
overlap, o uso de 200 caracteres produziu 222 chunks, enquanto 2000
caracteres resultaram em apenas 23 chunks.

A introdução de overlap aumentou a quantidade de chunks. Para chunks de
500 caracteres, foram obtidos 89 chunks sem overlap, 99 com overlap de
50 caracteres e 148 com overlap de 200 caracteres. Esse resultado evidencia
o aumento da redundância causado pela sobreposição.

As estratégias estruturais apresentaram comportamentos diferentes. O
chunking por parágrafos gerou 57 chunks e preservou melhor unidades textuais,
enquanto o agrupamento de três sentenças produziu 86 chunks com tamanhos
variáveis.

O RecursiveCharacterTextSplitter apresentou 65 chunks, buscando equilibrar
o limite de tamanho com a preservação da estrutura textual.

Por fim, o MarkdownHeaderTextSplitter gerou apenas 19 chunks, apresentando
a maior média de tamanho entre as estratégias. Apesar de preservar headings
e metadados estruturais, algumas seções resultaram em chunks muito extensos.

In [42]:
experimentos = {
    1: {
        "strategy": "fixed",
        "chunk_size": 200,
        "chunk_overlap": 0,
        "chunks": chunks
    },

    2: {
        "strategy": "fixed",
        "chunk_size": 500,
        "chunk_overlap": 0,
        "chunks": chunks_teste_2
    },

    3: {
        "strategy": "fixed",
        "chunk_size": 1000,
        "chunk_overlap": 0,
        "chunks": chunks_teste_3
    },

    4: {
        "strategy": "fixed",
        "chunk_size": 2000,
        "chunk_overlap": 0,
        "chunks": chunks_teste_4
    },

    5: {
        "strategy": "fixed_with_overlap",
        "chunk_size": 500,
        "chunk_overlap": 50,
        "chunks": chunks_teste_5
    },

    6: {
        "strategy": "fixed_with_overlap",
        "chunk_size": 500,
        "chunk_overlap": 200,
        "chunks": chunks_teste_6
    },

    7: {
        "strategy": "paragraph",
        "chunk_size": 1000,
        "chunk_overlap": 0,
        "chunks": chunks_teste_7
    },

    8: {
        "strategy": "sentence",
        "chunk_size": None,
        "chunk_overlap": 0,
        "chunks": chunks_teste_8
    },

    9: {
        "strategy": "recursive",
        "chunk_size": 1000,
        "chunk_overlap": 100,
        "chunks": chunks_teste_9
    },

    10: {
        "strategy": "markdown",
        "chunk_size": None,
        "chunk_overlap": 0,
        "chunks": chunks_teste_10
    }
}

In [43]:
for teste_id, config in experimentos.items():
    print(
        f"Teste {teste_id}: "
        f"{config['strategy']} - "
        f"{len(config['chunks'])} chunks"
    )

Teste 1: fixed - 222 chunks
Teste 2: fixed - 89 chunks
Teste 3: fixed - 45 chunks
Teste 4: fixed - 23 chunks
Teste 5: fixed_with_overlap - 99 chunks
Teste 6: fixed_with_overlap - 148 chunks
Teste 7: paragraph - 57 chunks
Teste 8: sentence - 86 chunks
Teste 9: recursive - 65 chunks
Teste 10: markdown - 19 chunks

## Geração dos Embeddings

Nesta etapa, será utilizado o mesmo modelo de embeddings para todos os
experimentos, garantindo uma comparação consistente entre as diferentes
estratégias de chunking.

Inicialmente, a geração será testada em um único chunk antes do
processamento completo dos experimentos.

In [44]:
def get_embedding(texto):
    response = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=texto,
        encoding_format="float"
    )

    return response.data[0].embedding

In [51]:
chunk_teste = experimentos[1]["chunks"][0]

print(chunk_teste)
print("\nTamanho:", len(chunk_teste))

273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medic

Tamanho: 200

In [52]:
embedding_teste = get_embedding(chunk_teste)

print("Dimensão do embedding:", len(embedding_teste))
print("Primeiros 10 valores:")
print(embedding_teste[:10])

Dimensão do embedding: 2048
Primeiros 10 valores:
[-0.026153564453125, -0.0074920654296875, 0.01483154296875, 0.0230712890625, 0.0091094970703125, -0.02410888671875, -0.01184844970703125, 0.0236968994140625, -0.04168701171875, 0.004970550537109375]

In [53]:
from dotenv import load_dotenv
import os
from openai import OpenAI

In [54]:
load_dotenv("../.env")

api_key = os.getenv("OPENROUTER_API_KEY")

print("Chave encontrada?", api_key is not None)

Chave encontrada? True

In [55]:
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key
)

In [56]:
import os
from dotenv import load_dotenv
from openai import OpenAI

# Carrega o arquivo .env que está na raiz AULA_01
load_dotenv("../.env")

api_key = os.getenv("OPENROUTER_API_KEY")

print("Chave encontrada?", api_key is not None)

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key
)

# Mesmo modelo utilizado na Aula 03
MODELO_EMBEDDING = "nvidia/llama-nemotron-embed-vl-1b-v2:free"

Chave encontrada? True

In [57]:
def get_embedding(texto):
    resposta = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=texto,
        encoding_format="float"
    )

    return resposta.data[0].embedding

In [50]:
chunk_teste = experimentos[1]["chunks"][0]

print("Texto que será enviado:")
print(chunk_teste)

embedding_teste = get_embedding(chunk_teste)

print("\nDimensão do embedding:", len(embedding_teste))
print("Primeiros 10 valores:")
print(embedding_teste[:10])

Texto que será enviado:
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medic

Dimensão do embedding: 2048
Primeiros 10 valores:
[-0.026153564453125, -0.0074920654296875, 0.01483154296875, 0.0230712890625, 0.0091094970703125, -0.02410888671875, -0.01184844970703125, 0.0236968994140625, -0.04168701171875, 0.004970550537109375]

In [58]:
import json
import time
from pathlib import Path

In [59]:
def obter_texto_chunk(chunk):
    if hasattr(chunk, "page_content"):
        return chunk.page_content
    return str(chunk)


def obter_metadata_chunk(chunk):
    if hasattr(chunk, "metadata"):
        return chunk.metadata
    return {}

In [60]:
resultados_embeddings = []

document_id = "doc01"
document_name = "bioetica_e_ia.md"

for teste_id, config in experimentos.items():

    print("=" * 60)
    print(f"PROCESSANDO TESTE {teste_id}")
    print(f"Estratégia: {config['strategy']}")
    print(f"Quantidade de chunks: {len(config['chunks'])}")

    for indice, chunk in enumerate(config["chunks"], start=1):

        texto_chunk = obter_texto_chunk(chunk)
        metadata = obter_metadata_chunk(chunk)

        try:
            embedding = get_embedding(texto_chunk)

            resultado = {
                "chunk_id": f"{document_id}_test{teste_id:02d}_chunk{indice:03d}",
                "document_id": document_id,
                "document_name": document_name,
                "test_id": teste_id,
                "strategy": config["strategy"],
                "chunk_size": config["chunk_size"],
                "chunk_overlap": config["chunk_overlap"],
                "text": texto_chunk,
                "embedding": embedding,
                "metadata": metadata
            }

            resultados_embeddings.append(resultado)

            print(
                f"Teste {teste_id} | "
                f"Chunk {indice}/{len(config['chunks'])} | "
                f"Embedding: {len(embedding)} dimensões"
            )

            # Pequena pausa para evitar muitas chamadas seguidas
            time.sleep(0.2)

        except Exception as erro:
            print(
                f"ERRO no Teste {teste_id}, "
                f"Chunk {indice}: {erro}"
            )

print("\nPROCESSAMENTO FINALIZADO")
print("Total de registros:", len(resultados_embeddings))

============================================================
PROCESSANDO TESTE 1
Estratégia: fixed
Quantidade de chunks: 222
Teste 1 | Chunk 1/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 2/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 3/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 4/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 5/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 6/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 7/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 8/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 9/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 10/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 11/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 12/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 13/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 14/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 15/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 16/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 17/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 18/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 19/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 20/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 21/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 22/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 23/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 24/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 25/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 26/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 27/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 28/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 29/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 30/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 31/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 32/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 33/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 34/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 35/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 36/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 37/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 38/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 39/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 40/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 41/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 42/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 43/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 44/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 45/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 46/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 47/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 48/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 49/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 50/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 51/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 52/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 53/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 54/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 55/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 56/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 57/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 58/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 59/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 60/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 61/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 62/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 63/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 64/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 65/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 66/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 67/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 68/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 69/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 70/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 71/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 72/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 73/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 74/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 75/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 76/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 77/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 78/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 79/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 80/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 81/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 82/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 83/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 84/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 85/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 86/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 87/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 88/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 89/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 90/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 91/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 92/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 93/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 94/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 95/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 96/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 97/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 98/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 99/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 100/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 101/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 102/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 103/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 104/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 105/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 106/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 107/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 108/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 109/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 110/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 111/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 112/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 113/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 114/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 115/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 116/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 117/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 118/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 119/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 120/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 121/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 122/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 123/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 124/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 125/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 126/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 127/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 128/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 129/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 130/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 131/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 132/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 133/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 134/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 135/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 136/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 137/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 138/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 139/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 140/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 141/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 142/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 143/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 144/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 145/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 146/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 147/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 148/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 149/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 150/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 151/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 152/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 153/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 154/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 155/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 156/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 157/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 158/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 159/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 160/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 161/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 162/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 163/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 164/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 165/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 166/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 167/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 168/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 169/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 170/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 171/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 172/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 173/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 174/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 175/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 176/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 177/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 178/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 179/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 180/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 181/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 182/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 183/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 184/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 185/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 186/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 187/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 188/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 189/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 190/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 191/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 192/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 193/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 194/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 195/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 196/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 197/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 198/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 199/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 200/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 201/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 202/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 203/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 204/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 205/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 206/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 207/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 208/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 209/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 210/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 211/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 212/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 213/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 214/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 215/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 216/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 217/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 218/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 219/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 220/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 221/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 222/222 | Embedding: 2048 dimensões
============================================================
PROCESSANDO TESTE 2
Estratégia: fixed
Quantidade de chunks: 89
Teste 2 | Chunk 1/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 2/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 3/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 4/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 5/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 6/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 7/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 8/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 9/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 10/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 11/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 12/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 13/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 14/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 15/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 16/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 17/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 18/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 19/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 20/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 21/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 22/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 23/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 24/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 25/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 26/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 27/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 28/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 29/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 30/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 31/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 32/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 33/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 34/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 35/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 36/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 37/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 38/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 39/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 40/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 41/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 42/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 43/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 44/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 45/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 46/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 47/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 48/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 49/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 50/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 51/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 52/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 53/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 54/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 55/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 56/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 57/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 58/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 59/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 60/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 61/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 62/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 63/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 64/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 65/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 66/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 67/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 68/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 69/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 70/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 71/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 72/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 73/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 74/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 75/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 76/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 77/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 78/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 79/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 80/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 81/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 82/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 83/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 84/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 85/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 86/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 87/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 88/89 | Embedding: 2048 dimensões
Teste 2 | Chunk 89/89 | Embedding: 2048 dimensões
============================================================
PROCESSANDO TESTE 3
Estratégia: fixed
Quantidade de chunks: 45
Teste 3 | Chunk 1/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 2/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 3/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 4/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 5/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 6/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 7/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 8/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 9/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 10/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 11/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 12/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 13/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 14/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 15/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 16/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 17/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 18/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 19/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 20/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 21/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 22/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 23/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 24/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 25/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 26/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 27/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 28/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 29/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 30/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 31/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 32/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 33/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 34/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 35/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 36/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 37/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 38/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 39/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 40/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 41/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 42/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 43/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 44/45 | Embedding: 2048 dimensões
Teste 3 | Chunk 45/45 | Embedding: 2048 dimensões
============================================================
PROCESSANDO TESTE 4
Estratégia: fixed
Quantidade de chunks: 23
Teste 4 | Chunk 1/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 2/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 3/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 4/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 5/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 6/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 7/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 8/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 9/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 10/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 11/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 12/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 13/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 14/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 15/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 16/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 17/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 18/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 19/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 20/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 21/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 22/23 | Embedding: 2048 dimensões
Teste 4 | Chunk 23/23 | Embedding: 2048 dimensões
============================================================
PROCESSANDO TESTE 5
Estratégia: fixed_with_overlap
Quantidade de chunks: 99
Teste 5 | Chunk 1/99 | Embedding: 2048 dimensões
Teste 5 | Chunk 2/99 | Embedding: 2048 dimensões

In [61]:
pasta_resultados = Path("results")
pasta_resultados.mkdir(exist_ok=True)

arquivo_saida = pasta_resultados / "bioetica_e_ia_chunking_embeddings.json"

with open(arquivo_saida, "w", encoding="utf-8") as arquivo:
    json.dump(
        resultados_embeddings,
        arquivo,
        ensure_ascii=False,
        indent=2
    )

print("JSON salvo em:")
print(arquivo_saida)

JSON salvo em:
results\bioetica_e_ia_chunking_embeddings.json

In [62]:
summary = {
    "document": "bioetica_e_ia.md",
    "embedding_model": MODELO_EMBEDDING,
    "embedding_dimension": len(embedding_teste),
    "experiments": []
}

for teste_id, config in experimentos.items():

    chunks_config = config["chunks"]

    if teste_id == 10:
        tamanhos_config = [
            len(chunk.page_content)
            for chunk in chunks_config
        ]
    else:
        tamanhos_config = [
            len(str(chunk))
            for chunk in chunks_config
        ]

    summary["experiments"].append({
        "test_id": teste_id,
        "strategy": config["strategy"],
        "chunk_size": config["chunk_size"],
        "chunk_overlap": config["chunk_overlap"],
        "num_chunks": len(chunks_config),
        "avg_chunk_size": round(
            sum(tamanhos_config) / len(tamanhos_config),
            2
        ),
        "min_chunk_size": min(tamanhos_config),
        "max_chunk_size": max(tamanhos_config),
        "embedding_dimension": len(embedding_teste)
    })

In [63]:
arquivo_summary = Path("results") / "summary.json"

with open(arquivo_summary, "w", encoding="utf-8") as arquivo:
    json.dump(
        summary,
        arquivo,
        ensure_ascii=False,
        indent=2
    )

print("Summary criado:")
print(arquivo_summary)

Summary criado:
results\summary.json

# Análise dos Experimentos

## 1. Qual estratégia gerou mais chunks?

Entre os experimentos realizados, a estratégia com maior número de chunks foi o
Teste 1, com chunk_size de 200 caracteres e sem overlap.

Esse comportamento era esperado, pois quanto menor o tamanho máximo permitido
para cada chunk, maior é a quantidade de fragmentos necessários para representar
o documento completo.

## 2. Qual estratégia gerou menos chunks?

A estratégia que gerou menos chunks foi o MarkdownHeaderTextSplitter.

Essa estratégia utiliza a estrutura de headings do documento para definir as
divisões, produzindo menos chunks, porém com tamanhos significativamente maiores
e mais variáveis.

## 3. Como o tamanho dos chunks variou?

As estratégias baseadas em tamanho fixo produziram chunks mais uniformes.

Nos testes com 200, 500, 1000 e 2000 caracteres, o tamanho dos chunks se manteve
próximo ao limite configurado.

Já as estratégias baseadas em parágrafos, sentenças e headings apresentaram maior
variação, pois priorizam unidades estruturais ou semânticas do texto em vez de
limites rígidos de tamanho.

## 4. Qual estratégia preservou melhor a estrutura dos documentos?

O MarkdownHeaderTextSplitter apresentou a melhor preservação da estrutura
documental, pois manteve informações associadas aos headings e seções.

O chunking por parágrafos também preservou melhor a estrutura textual do que os
métodos puramente baseados em caracteres.

## 5. Como tabelas foram tratadas?

As tabelas já haviam sido convertidas para a representação Markdown durante a
etapa PDF → Markdown.

Nos chunkings baseados em caracteres, existe risco de fragmentação das linhas e
da estrutura da tabela.

Estratégias estruturais, especialmente Markdown e Recursive, tendem a apresentar
maior possibilidade de preservação, dependendo da posição e do tamanho da tabela.

## 6. Como imagens foram tratadas?

Durante a conversão para Markdown, algumas imagens foram representadas por
marcadores como:

`<!-- image -->`

Isso indica que a imagem em si não foi incorporada como conteúdo visual no
Markdown utilizado pelos experimentos.

Assim, o embedding textual não representa diretamente o conteúdo visual da
imagem.

## 7. Quais informações foram perdidas durante a conversão PDF → Markdown?

Foi possível observar perda parcial da estrutura visual original do PDF.

Entre os elementos afetados estão layout de páginas, posicionamento de imagens,
colunas, espaçamento e parte da formatação visual.

Também foram observadas palavras fragmentadas por hifenização proveniente do PDF.

## 8. O chunking por caracteres fragmentou conceitos ou estruturas importantes?

Sim.

Os testes de chunking fixo apresentaram cortes no meio de palavras, frases e
parágrafos.

Isso demonstra que a divisão baseada exclusivamente em número de caracteres pode
prejudicar a preservação do contexto semântico.

## 9. O chunking por parágrafo produziu chunks muito grandes?

Em alguns casos, sim.

Como determinados parágrafos possuíam mais caracteres do que o tamanho definido,
alguns chunks ultrapassaram o valor configurado.

Esse resultado mostra o equilíbrio necessário entre preservação semântica e
controle do tamanho dos chunks.

## 10. O chunking por sentença conseguiu preservar melhor o contexto?

O agrupamento de três sentenças reduziu os cortes arbitrários encontrados nas
estratégias baseadas em caracteres.

Essa abordagem preservou unidades completas de sentido, embora tenha produzido
chunks de tamanhos variados.

## 11. O Recursive Splitter apresentou vantagens?

Sim.

O RecursiveCharacterTextSplitter apresentou um equilíbrio entre controle de
tamanho e preservação da estrutura textual.

A estratégia tenta inicialmente separar por parágrafos, depois por linhas,
espaços e, por último, caracteres.

Isso reduz a fragmentação arbitrária quando comparado ao chunking fixo.

## 12. O Markdown Splitter conseguiu preservar a estrutura semântica?

Sim.

O MarkdownHeaderTextSplitter conseguiu associar conteúdo aos headings e preservar
metadados relacionados às seções.

Essa característica pode ser especialmente útil em sistemas de RAG, pois permite
recuperar não apenas o texto, mas também informações sobre a seção de origem.

## 13. Qual estratégia parece mais adequada para um sistema de RAG?

Entre as estratégias avaliadas, o RecursiveCharacterTextSplitter apresenta uma
boa relação entre tamanho dos chunks e preservação do contexto.

O MarkdownHeaderTextSplitter também apresentou vantagens importantes na
preservação da estrutura semântica.

Uma abordagem híbrida, combinando headings Markdown com uma subdivisão recursiva
das seções muito grandes, pode ser uma alternativa adequada para RAG.

## 14. Quais estratégias devem ser descartadas?

Os chunkings fixos muito pequenos, especialmente o de 200 caracteres, tendem a
fragmentar excessivamente o conteúdo e gerar grande quantidade de embeddings.

O overlap muito alto também pode ser menos interessante devido à grande
redundância e ao aumento do custo de processamento e armazenamento.

## 15. Quais estratégias devem ser utilizadas nos próximos experimentos?

As estratégias mais interessantes para os próximos testes são:

- RecursiveCharacterTextSplitter;
- MarkdownHeaderTextSplitter;
- chunking por parágrafos;
- eventualmente chunk fixo intermediário com overlap leve, como 500 caracteres
  com overlap 50, para comparação.

Essas estratégias apresentam melhor equilíbrio entre preservação de contexto,
estrutura semântica, quantidade de chunks e custo de processamento.

## Conversão automática dos PDFs para Markdown

Nesta etapa, todos os arquivos PDF presentes na pasta `artigos`
serão convertidos automaticamente para Markdown utilizando o Docling.

Os arquivos resultantes serão armazenados na pasta `markdown`.

In [64]:
import os
import gc
from pathlib import Path

# Reduz consumo de memória no Windows
os.environ["TORCH_COMPILE_DISABLE"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"

from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption


PASTA_ARTIGOS = Path("artigos")
PASTA_MARKDOWN = Path("markdown")

PASTA_MARKDOWN.mkdir(
    parents=True,
    exist_ok=True
)


# Configuração mais leve do Docling
pipeline_options = PdfPipelineOptions()

# Como os artigos científicos normalmente já possuem texto digital,
# não precisamos usar OCR.
pipeline_options.do_ocr = False

# Mantemos análise de tabelas.
pipeline_options.do_table_structure = True

# Reduz uso de memória
pipeline_options.layout_batch_size = 1
pipeline_options.ocr_batch_size = 1
pipeline_options.table_batch_size = 1


converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(
            pipeline_options=pipeline_options
        )
    }
)


arquivos_pdf = sorted(
    PASTA_ARTIGOS.glob("*.pdf")
)

print(
    "Quantidade de PDFs encontrados:",
    len(arquivos_pdf)
)

Quantidade de PDFs encontrados: 12

In [2]:
import os
import gc

os.environ["TORCH_COMPILE_DISABLE"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"

from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption

pipeline_options = PdfPipelineOptions()

# PDFs acadêmicos já possuem texto digital
pipeline_options.do_ocr = False

# Vamos deixar desligado agora para consumir menos memória
pipeline_options.do_table_structure = False

# Reduz o processamento simultâneo
pipeline_options.layout_batch_size = 1
pipeline_options.ocr_batch_size = 1
pipeline_options.table_batch_size = 1

converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(
            pipeline_options=pipeline_options
        )
    }
)

print("✅ Conversor Docling criado!")

c:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

✅ Conversor Docling criado!

In [6]:
%pip install pypdf

Collecting pypdf
  Downloading pypdf-6.15.0-py3-none-any.whl.metadata (7.5 kB)
Downloading pypdf-6.15.0-py3-none-any.whl (378 kB)
Installing collected packages: pypdf
Successfully installed pypdf-6.15.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
from pypdf import PdfReader

print("✅ pypdf funcionando!")

✅ pypdf funcionando!

In [8]:
from pathlib import Path
from pypdf import PdfReader
import gc

arquivo_pdf = Path("artigos/gpt3_language_models.pdf")
arquivo_saida = Path("markdown/gpt3_language_models.md")

# Processar apenas 2 páginas por vez
TAMANHO_BLOCO = 2

reader = PdfReader(str(arquivo_pdf))
total_paginas = len(reader.pages)

print("Arquivo:", arquivo_pdf.name)
print("Total de páginas:", total_paginas)
print("=" * 60)

partes_markdown = []

for inicio in range(1, total_paginas + 1, TAMANHO_BLOCO):
    fim = min(inicio + TAMANHO_BLOCO - 1, total_paginas)

    print(
        f"⏳ Processando páginas {inicio}-{fim} de {total_paginas}...",
        flush=True
    )

    try:
        resultado = converter.convert(
            arquivo_pdf,
            page_range=(inicio, fim)
        )

        markdown_parcial = resultado.document.export_to_markdown()

        partes_markdown.append(markdown_parcial)

        print(
            f"✅ Páginas {inicio}-{fim} concluídas!",
            flush=True
        )

        del resultado
        del markdown_parcial
        gc.collect()

    except Exception as erro:
        print(
            f"❌ ERRO nas páginas {inicio}-{fim}: {erro}",
            flush=True
        )
        gc.collect()

markdown_completo = "\n\n".join(partes_markdown)

arquivo_saida.write_text(
    markdown_completo,
    encoding="utf-8"
)

print("\n" + "=" * 60)
print("✅ CONVERSÃO FINALIZADA")
print("Arquivo criado:", arquivo_saida)
print("Tamanho:", arquivo_saida.stat().st_size, "bytes")

Arquivo: gpt3_language_models.pdf
Total de páginas: 75
============================================================
⏳ Processando páginas 1-2 de 75...

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 1272.08it/s]

✅ Páginas 1-2 concluídas!
⏳ Processando páginas 3-4 de 75...
✅ Páginas 3-4 concluídas!
⏳ Processando páginas 5-6 de 75...
✅ Páginas 5-6 concluídas!
⏳ Processando páginas 7-8 de 75...
✅ Páginas 7-8 concluídas!
⏳ Processando páginas 9-10 de 75...
✅ Páginas 9-10 concluídas!
⏳ Processando páginas 11-12 de 75...
✅ Páginas 11-12 concluídas!
⏳ Processando páginas 13-14 de 75...
✅ Páginas 13-14 concluídas!
⏳ Processando páginas 15-16 de 75...
✅ Páginas 15-16 concluídas!
⏳ Processando páginas 17-18 de 75...
✅ Páginas 17-18 concluídas!
⏳ Processando páginas 19-20 de 75...
✅ Páginas 19-20 concluídas!
⏳ Processando páginas 21-22 de 75...
✅ Páginas 21-22 concluídas!
⏳ Processando páginas 23-24 de 75...
✅ Páginas 23-24 concluídas!
⏳ Processando páginas 25-26 de 75...
✅ Páginas 25-26 concluídas!
⏳ Processando páginas 27-28 de 75...
✅ Páginas 27-28 concluídas!
⏳ Processando páginas 29-30 de 75...
✅ Páginas 29-30 concluídas!
⏳ Processando páginas 31-32 de 75...
✅ Páginas 31-32 concluídas!
⏳ Processando páginas 33-34 de 75...
✅ Páginas 33-34 concluídas!
⏳ Processando páginas 35-36 de 75...
✅ Páginas 35-36 concluídas!
⏳ Processando páginas 37-38 de 75...
✅ Páginas 37-38 concluídas!
⏳ Processando páginas 39-40 de 75...
✅ Páginas 39-40 concluídas!
⏳ Processando páginas 41-42 de 75...
✅ Páginas 41-42 concluídas!
⏳ Processando páginas 43-44 de 75...
✅ Páginas 43-44 concluídas!
⏳ Processando páginas 45-46 de 75...
✅ Páginas 45-46 concluídas!
⏳ Processando páginas 47-48 de 75...
✅ Páginas 47-48 concluídas!
⏳ Processando páginas 49-50 de 75...
✅ Páginas 49-50 concluídas!
⏳ Processando páginas 51-52 de 75...
✅ Páginas 51-52 concluídas!
⏳ Processando páginas 53-54 de 75...
✅ Páginas 53-54 concluídas!
⏳ Processando páginas 55-56 de 75...
✅ Páginas 55-56 concluídas!
⏳ Processando páginas 57-58 de 75...
✅ Páginas 57-58 concluídas!
⏳ Processando páginas 59-60 de 75...
✅ Páginas 59-60 concluídas!
⏳ Processando páginas 61-62 de 75...
✅ Páginas 61-62 concluídas!
⏳ Processando páginas 63-64 de 75...
✅ Páginas 63-64 concluídas!
⏳ Processando páginas 65-66 de 75...
✅ Páginas 65-66 concluídas!
⏳ Processando páginas 67-68 de 75...
✅ Páginas 67-68 concluídas!
⏳ Processando páginas 69-70 de 75...
✅ Páginas 69-70 concluídas!
⏳ Processando páginas 71-72 de 75...
✅ Páginas 71-72 concluídas!
⏳ Processando páginas 73-74 de 75...
✅ Páginas 73-74 concluídas!
⏳ Processando páginas 75-75 de 75...
✅ Páginas 75-75 concluídas!

============================================================
✅ CONVERSÃO FINALIZADA
Arquivo criado: markdown\gpt3_language_models.md
Tamanho: 288939 bytes

In [15]:
from pathlib import Path
from pypdf import PdfReader
import gc

# ============================================================
# ARQUIVO QUE SERÁ CONVERTIDO
# ============================================================

arquivo_pdf = Path("artigos/scaling_laws_llm.pdf")
arquivo_saida = Path("markdown/scaling_laws_llm.md")
# Quantidade de páginas processadas por vez
TAMANHO_BLOCO = 2


# ============================================================
# VERIFICAR QUANTIDADE DE PÁGINAS
# ============================================================

reader = PdfReader(str(arquivo_pdf))
total_paginas = len(reader.pages)

print("Arquivo:", arquivo_pdf.name)
print("Total de páginas:", total_paginas)
print("=" * 60)


# ============================================================
# CONVERSÃO EM BLOCOS
# ============================================================

partes_markdown = []

for inicio in range(1, total_paginas + 1, TAMANHO_BLOCO):

    fim = min(
        inicio + TAMANHO_BLOCO - 1,
        total_paginas
    )

    print(
        f"⏳ Processando páginas {inicio}-{fim} "
        f"de {total_paginas}...",
        flush=True
    )

    try:

        resultado = converter.convert(
            arquivo_pdf,
            page_range=(inicio, fim)
        )

        markdown_parcial = (
            resultado.document.export_to_markdown()
        )

        partes_markdown.append(
            markdown_parcial
        )

        print(
            f"✅ Páginas {inicio}-{fim} concluídas!",
            flush=True
        )

        # Libera memória
        del resultado
        del markdown_parcial
        gc.collect()

    except Exception as erro:

        print(
            f"❌ ERRO nas páginas "
            f"{inicio}-{fim}: {erro}",
            flush=True
        )

        gc.collect()


# ============================================================
# JUNTAR TODOS OS BLOCOS
# ============================================================

markdown_completo = "\n\n".join(
    partes_markdown
)


# ============================================================
# SALVAR O MARKDOWN
# ============================================================

arquivo_saida.write_text(
    markdown_completo,
    encoding="utf-8"
)


# ============================================================
# RESULTADO
# ============================================================

print("\n" + "=" * 60)
print("✅ CONVERSÃO FINALIZADA")
print("Arquivo criado:", arquivo_saida)
print(
    "Tamanho:",
    arquivo_saida.stat().st_size,
    "bytes"
)

Arquivo: scaling_laws_llm.pdf
Total de páginas: 30
============================================================
⏳ Processando páginas 1-2 de 30...
✅ Páginas 1-2 concluídas!
⏳ Processando páginas 3-4 de 30...
✅ Páginas 3-4 concluídas!
⏳ Processando páginas 5-6 de 30...
✅ Páginas 5-6 concluídas!
⏳ Processando páginas 7-8 de 30...
✅ Páginas 7-8 concluídas!
⏳ Processando páginas 9-10 de 30...
✅ Páginas 9-10 concluídas!
⏳ Processando páginas 11-12 de 30...
✅ Páginas 11-12 concluídas!
⏳ Processando páginas 13-14 de 30...
✅ Páginas 13-14 concluídas!
⏳ Processando páginas 15-16 de 30...
✅ Páginas 15-16 concluídas!
⏳ Processando páginas 17-18 de 30...
✅ Páginas 17-18 concluídas!
⏳ Processando páginas 19-20 de 30...
✅ Páginas 19-20 concluídas!
⏳ Processando páginas 21-22 de 30...
✅ Páginas 21-22 concluídas!
⏳ Processando páginas 23-24 de 30...
✅ Páginas 23-24 concluídas!
⏳ Processando páginas 25-26 de 30...
✅ Páginas 25-26 concluídas!
⏳ Processando páginas 27-28 de 30...
✅ Páginas 27-28 concluídas!
⏳ Processando páginas 29-30 de 30...
✅ Páginas 29-30 concluídas!

============================================================
✅ CONVERSÃO FINALIZADA
Arquivo criado: markdown\scaling_laws_llm.md
Tamanho: 96800 bytes

In [16]:
from pathlib import Path

PASTA_ARTIGOS = Path("artigos")
PASTA_MARKDOWN = Path("markdown")

pdfs = sorted(PASTA_ARTIGOS.glob("*.pdf"))
mds = sorted(PASTA_MARKDOWN.glob("*.md"))

print("=" * 70)
print("VERIFICAÇÃO PDF → MARKDOWN")
print("=" * 70)

quantidade_ok = 0
faltando = []

for pdf in pdfs:
    md_esperado = PASTA_MARKDOWN / f"{pdf.stem}.md"

    if md_esperado.exists():
        tamanho = md_esperado.stat().st_size

        print(
            f"✅ OK     {pdf.name} "
            f"→ {md_esperado.name} "
            f"({tamanho:,} bytes)"
        )

        quantidade_ok += 1

    else:
        print(
            f"❌ FALTA  {pdf.name}"
        )

        faltando.append(pdf.name)

print("\n" + "=" * 70)
print("RESUMO")
print("=" * 70)

print("Total de PDFs:", len(pdfs))
print("Com Markdown:", quantidade_ok)
print("Faltando:", len(faltando))

if len(faltando) == 0:
    print("\n🎉 Todos os PDFs possuem arquivo Markdown!")
else:
    print("\n⚠️ PDFs ainda sem Markdown:")

    for nome in faltando:
        print(" -", nome)

======================================================================
VERIFICAÇÃO PDF → MARKDOWN
======================================================================
✅ OK     attention_is_all_you_need.pdf → attention_is_all_you_need.md (11,580 bytes)
✅ OK     bert_pretraining.pdf → bert_pretraining.md (38,218 bytes)
✅ OK     bioetica_e_ia.pdf → bioetica_e_ia.md (46,033 bytes)
✅ OK     escrita_academica_ia.pdf → escrita_academica_ia.md (36,911 bytes)
✅ OK     gpt3_language_models.pdf → gpt3_language_models.md (288,939 bytes)
✅ OK     gpt4_technical_report.pdf → gpt4_technical_report.md (283,980 bytes)
✅ OK     instruct_gpt.pdf → instruct_gpt.md (205,631 bytes)
✅ OK     llama_foundation_models.pdf → llama_foundation_models.md (101,599 bytes)
✅ OK     lora_low_rank_adaptation.pdf → lora_low_rank_adaptation.md (97,723 bytes)
✅ OK     retrieval_augmented_generation.pdf → retrieval_augmented_generation.md (71,875 bytes)
✅ OK     scaling_laws_llm.pdf → scaling_laws_llm.md (96,800 bytes)
✅ OK     twitter_algoritmo.pdf → twitter_algoritmo.md (37,062 bytes)

======================================================================
RESUMO
======================================================================
Total de PDFs: 12
Com Markdown: 12
Faltando: 0

🎉 Todos os PDFs possuem arquivo Markdown!

In [17]:
import json
from pathlib import Path

from langchain_text_splitters import (
    RecursiveCharacterTextSplitter,
    MarkdownHeaderTextSplitter,
)

# ============================================================
# PASTAS
# ============================================================

PASTA_MARKDOWN = Path("markdown")
PASTA_RESULTS = Path("results")

PASTA_RESULTS.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# SPLITTERS
# ============================================================

# 1. Recursive
splitter_recursive = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100,
    separators=[
        "\n\n",
        "\n",
        " ",
        ""
    ],
    length_function=len
)

# 2. Markdown por headings
headers_to_split_on = [
    ("#", "titulo_nivel_1"),
    ("##", "titulo_nivel_2"),
    ("###", "titulo_nivel_3"),
]

splitter_markdown = MarkdownHeaderTextSplitter(
    headers_to_split_on=headers_to_split_on
)


# ============================================================
# FUNÇÃO PARA CHUNKING POR PARÁGRAFOS
# ============================================================

def chunking_paragrafos(texto):
    """
    Divide o texto preservando parágrafos como unidades.
    """
    paragrafos = [
        p.strip()
        for p in texto.split("\n\n")
        if p.strip()
    ]

    return paragrafos


# ============================================================
# FUNÇÃO PARA SALVAR JSON
# ============================================================

def salvar_json(caminho, dados):
    caminho.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        caminho,
        "w",
        encoding="utf-8"
    ) as arquivo:

        json.dump(
            dados,
            arquivo,
            ensure_ascii=False,
            indent=2
        )


# ============================================================
# PROCESSAR TODOS OS MARKDOWNS
# ============================================================

arquivos_md = sorted(
    PASTA_MARKDOWN.glob("*.md")
)

print(
    "Quantidade de documentos:",
    len(arquivos_md)
)

print("=" * 70)


for indice_doc, arquivo_md in enumerate(
    arquivos_md,
    start=1
):

    document_id = f"doc{indice_doc:02d}"
    document_name = arquivo_md.name
    document_slug = arquivo_md.stem

    print(
        f"\n[{indice_doc}/{len(arquivos_md)}] "
        f"Processando: {document_name}"
    )

    texto = arquivo_md.read_text(
        encoding="utf-8"
    )

    pasta_documento = (
        PASTA_RESULTS / document_slug
    )

    # ========================================================
    # ESTRATÉGIA 1 - RECURSIVE
    # ========================================================

    chunks_recursive = (
        splitter_recursive.split_text(texto)
    )

    dados_recursive = []

    for indice_chunk, chunk in enumerate(
        chunks_recursive,
        start=1
    ):

        dados_recursive.append({
            "chunk_id": (
                f"{document_id}_recursive_"
                f"chunk{indice_chunk:03d}"
            ),
            "document_id": document_id,
            "document_name": document_name,
            "strategy": "recursive",
            "chunk_size": 1000,
            "chunk_overlap": 100,
            "text": chunk,
            "metadata": {}
        })

    salvar_json(
        pasta_documento
        / "recursive"
        / "chunks.json",
        dados_recursive
    )

    print(
        f"  ✅ Recursive: "
        f"{len(chunks_recursive)} chunks"
    )


    # ========================================================
    # ESTRATÉGIA 2 - PARÁGRAFOS
    # ========================================================

    chunks_paragrafos = (
        chunking_paragrafos(texto)
    )

    dados_paragrafos = []

    for indice_chunk, chunk in enumerate(
        chunks_paragrafos,
        start=1
    ):

        dados_paragrafos.append({
            "chunk_id": (
                f"{document_id}_paragraph_"
                f"chunk{indice_chunk:03d}"
            ),
            "document_id": document_id,
            "document_name": document_name,
            "strategy": "paragraph",
            "chunk_size": None,
            "chunk_overlap": 0,
            "text": chunk,
            "metadata": {}
        })

    salvar_json(
        pasta_documento
        / "paragraph"
        / "chunks.json",
        dados_paragrafos
    )

    print(
        f"  ✅ Paragraph: "
        f"{len(chunks_paragrafos)} chunks"
    )


    # ========================================================
    # ESTRATÉGIA 3 - MARKDOWN HEADINGS
    # ========================================================

    chunks_markdown = (
        splitter_markdown.split_text(texto)
    )

    dados_markdown = []

    for indice_chunk, chunk in enumerate(
        chunks_markdown,
        start=1
    ):

        dados_markdown.append({
            "chunk_id": (
                f"{document_id}_markdown_"
                f"chunk{indice_chunk:03d}"
            ),
            "document_id": document_id,
            "document_name": document_name,
            "strategy": "markdown",
            "chunk_size": None,
            "chunk_overlap": 0,
            "text": chunk.page_content,
            "metadata": chunk.metadata
        })

    salvar_json(
        pasta_documento
        / "markdown"
        / "chunks.json",
        dados_markdown
    )

    print(
        f"  ✅ Markdown: "
        f"{len(chunks_markdown)} chunks"
    )


print("\n" + "=" * 70)
print("🎉 PROCESSAMENTO FINALIZADO!")

Quantidade de documentos: 12
======================================================================

[1/12] Processando: attention_is_all_you_need.md
  ✅ Recursive: 15 chunks
  ✅ Paragraph: 44 chunks
  ✅ Markdown: 11 chunks

[2/12] Processando: bert_pretraining.md
  ✅ Recursive: 52 chunks
  ✅ Paragraph: 109 chunks
  ✅ Markdown: 18 chunks

[3/12] Processando: bioetica_e_ia.md
  ✅ Recursive: 65 chunks
  ✅ Paragraph: 112 chunks
  ✅ Markdown: 19 chunks

[4/12] Processando: escrita_academica_ia.md
  ✅ Recursive: 50 chunks
  ✅ Paragraph: 89 chunks
  ✅ Markdown: 14 chunks

[5/12] Processando: gpt3_language_models.md
  ✅ Recursive: 412 chunks
  ✅ Paragraph: 593 chunks
  ✅ Markdown: 55 chunks

[6/12] Processando: gpt4_technical_report.md
  ✅ Recursive: 386 chunks
  ✅ Paragraph: 1039 chunks
  ✅ Markdown: 195 chunks

[7/12] Processando: instruct_gpt.md
  ✅ Recursive: 272 chunks
  ✅ Paragraph: 632 chunks
  ✅ Markdown: 116 chunks

[8/12] Processando: llama_foundation_models.md
  ✅ Recursive: 137 chunks
  ✅ Paragraph: 285 chunks
  ✅ Markdown: 54 chunks

[9/12] Processando: lora_low_rank_adaptation.md
  ✅ Recursive: 135 chunks
  ✅ Paragraph: 227 chunks
  ✅ Markdown: 38 chunks

[10/12] Processando: retrieval_augmented_generation.md
  ✅ Recursive: 105 chunks
  ✅ Paragraph: 134 chunks
  ✅ Markdown: 33 chunks

[11/12] Processando: scaling_laws_llm.md
  ✅ Recursive: 127 chunks
  ✅ Paragraph: 366 chunks
  ✅ Markdown: 49 chunks

[12/12] Processando: twitter_algoritmo.md
  ✅ Recursive: 52 chunks
  ✅ Paragraph: 86 chunks
  ✅ Markdown: 11 chunks

======================================================================
🎉 PROCESSAMENTO FINALIZADO!

In [18]:
def get_embeddings_batch(textos):
    resposta = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=textos,
        encoding_format="float"
    )

    return [
        item.embedding
        for item in resposta.data
    ]

In [19]:
import json
from pathlib import Path

arquivo_teste = Path(
    "results/attention_is_all_you_need/recursive/chunks.json"
)

with open(
    arquivo_teste,
    "r",
    encoding="utf-8"
) as arquivo:
    chunks_teste = json.load(arquivo)

textos_teste = [
    item["text"]
    for item in chunks_teste[:5]
]

embeddings_teste = get_embeddings_batch(
    textos_teste
)

print("Quantidade de textos:", len(textos_teste))
print("Quantidade de embeddings:", len(embeddings_teste))
print(
    "Dimensão de cada embedding:",
    len(embeddings_teste[0])
)

NameError: name 'client' is not defined

In [20]:
import os
from openai import OpenAI

# Coloque sua chave do OpenRouter aqui APENAS para executar localmente
OPENROUTER_API_KEY = "SUA_CHAVE_AQUI"

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY
)

print("✅ Cliente OpenRouter configurado!")

✅ Cliente OpenRouter configurado!

In [21]:
def get_embeddings_batch(textos):
    resposta = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=textos,
        encoding_format="float"
    )

    return [
        item.embedding
        for item in resposta.data
    ]

In [23]:
MODELO_EMBEDDING = "nvidia/llama-nemotron-embed-vl-1b-v2:free"

print("Modelo:", MODELO_EMBEDDING)

Modelo: nvidia/llama-nemotron-embed-vl-1b-v2:free

In [25]:
def get_embeddings_batch(textos):
    resposta = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=textos,
        encoding_format="float"
    )

    return [
        item.embedding
        for item in resposta.data
    ]

In [26]:
embeddings_teste = get_embeddings_batch(textos_teste)

print("Quantidade de textos:", len(textos_teste))
print("Quantidade de embeddings:", len(embeddings_teste))
print("Dimensão:", len(embeddings_teste[0]))

AuthenticationError: Error code: 401 - {'error': {'message': 'Missing Authentication header', 'code': 401}}

In [27]:
import os
from dotenv import load_dotenv
from openai import OpenAI

# Carrega o arquivo .env da raiz do projeto
load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

if not OPENROUTER_API_KEY:
    raise ValueError("❌ OPENROUTER_API_KEY não encontrada no arquivo .env")

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY
)

print("✅ Chave encontrada!")
print("✅ Cliente OpenRouter configurado!")

✅ Chave encontrada!
✅ Cliente OpenRouter configurado!

In [28]:
embeddings_teste = get_embeddings_batch(textos_teste)

print("Quantidade de textos:", len(textos_teste))
print("Quantidade de embeddings:", len(embeddings_teste))
print("Dimensão:", len(embeddings_teste[0]))

Quantidade de textos: 5
Quantidade de embeddings: 5
Dimensão: 2048

In [31]:
import json
import time
from pathlib import Path

PASTA_RESULTS = Path("results")

TAMANHO_LOTE = 1
PAUSA_ENTRE_LOTES = 0.5

arquivos_chunks = sorted(
    PASTA_RESULTS.glob("*/*/chunks.json")
)

print("Arquivos encontrados:", len(arquivos_chunks))
print("=" * 70)

for numero_arquivo, arquivo_chunks in enumerate(
    arquivos_chunks,
    start=1
):

    arquivo_saida = (
        arquivo_chunks.parent
        / "chunks_embeddings.json"
    )

    print(
        f"\n[{numero_arquivo}/{len(arquivos_chunks)}] "
        f"Processando: {arquivo_chunks}"
    )

    # Se já existir, não processa novamente
    if arquivo_saida.exists():
        print("✅ Já existe. Ignorado.")
        continue

    with open(
        arquivo_chunks,
        "r",
        encoding="utf-8"
    ) as arquivo:
        dados = json.load(arquivo)

    total_chunks = len(dados)

    print("Chunks:", total_chunks)

    resultados = []

    for inicio in range(
        0,
        total_chunks,
        TAMANHO_LOTE
    ):

        fim = min(
            inicio + TAMANHO_LOTE,
            total_chunks
        )

        lote = dados[inicio:fim]

        textos = [
            item["text"]
            for item in lote
        ]

        print(
            f"  ⏳ Embeddings "
            f"{inicio + 1}-{fim}/{total_chunks}...",
            flush=True
        )

        try:
            embeddings = get_embeddings_batch(
                textos
            )

            for item, embedding in zip(
                lote,
                embeddings
            ):
                item_com_embedding = item.copy()

                item_com_embedding[
                    "embedding"
                ] = embedding

                resultados.append(
                    item_com_embedding
                )

            print(
                f"  ✅ Lote {inicio + 1}-{fim} concluído",
                flush=True
            )

            time.sleep(PAUSA_ENTRE_LOTES)

        except Exception as erro:
            print(
                f"  ❌ ERRO no lote "
                f"{inicio + 1}-{fim}: {erro}",
                flush=True
            )

            print(
                "Processamento interrompido "
                "para evitar perda de controle."
            )

            break

    # Só salva se todos os chunks foram processados
    if len(resultados) == total_chunks:

        with open(
            arquivo_saida,
            "w",
            encoding="utf-8"
        ) as arquivo:

            json.dump(
                resultados,
                arquivo,
                ensure_ascii=False,
                indent=2
            )

        print(
            f"✅ Arquivo salvo: "
            f"{arquivo_saida}"
        )

    else:
        print(
            f"⚠️ Arquivo não salvo porque "
            f"foram processados "
            f"{len(resultados)}/{total_chunks} chunks."
        )


print("\n" + "=" * 70)
print("PROCESSAMENTO FINALIZADO")

Arquivos encontrados: 36
======================================================================

[1/36] Processando: results\attention_is_all_you_need\markdown\chunks.json
✅ Já existe. Ignorado.

[2/36] Processando: results\attention_is_all_you_need\paragraph\chunks.json
✅ Já existe. Ignorado.

[3/36] Processando: results\attention_is_all_you_need\recursive\chunks.json
✅ Já existe. Ignorado.

[4/36] Processando: results\bert_pretraining\markdown\chunks.json
✅ Já existe. Ignorado.

[5/36] Processando: results\bert_pretraining\paragraph\chunks.json
✅ Já existe. Ignorado.

[6/36] Processando: results\bert_pretraining\recursive\chunks.json
✅ Já existe. Ignorado.

[7/36] Processando: results\bioetica_e_ia\markdown\chunks.json
✅ Já existe. Ignorado.

[8/36] Processando: results\bioetica_e_ia\paragraph\chunks.json
✅ Já existe. Ignorado.

[9/36] Processando: results\bioetica_e_ia\recursive\chunks.json
✅ Já existe. Ignorado.

[10/36] Processando: results\escrita_academica_ia\markdown\chunks.json
✅ Já existe. Ignorado.

[11/36] Processando: results\escrita_academica_ia\paragraph\chunks.json
✅ Já existe. Ignorado.

[12/36] Processando: results\escrita_academica_ia\recursive\chunks.json
✅ Já existe. Ignorado.

[13/36] Processando: results\gpt3_language_models\markdown\chunks.json
Chunks: 55
  ⏳ Embeddings 1-1/55...

  ✅ Lote 1-1 concluído
  ⏳ Embeddings 2-2/55...
  ✅ Lote 2-2 concluído
  ⏳ Embeddings 3-3/55...
  ✅ Lote 3-3 concluído
  ⏳ Embeddings 4-4/55...
  ✅ Lote 4-4 concluído
  ⏳ Embeddings 5-5/55...
  ✅ Lote 5-5 concluído
  ⏳ Embeddings 6-6/55...
  ✅ Lote 6-6 concluído
  ⏳ Embeddings 7-7/55...
  ✅ Lote 7-7 concluído
  ⏳ Embeddings 8-8/55...
  ✅ Lote 8-8 concluído
  ⏳ Embeddings 9-9/55...
  ✅ Lote 9-9 concluído
  ⏳ Embeddings 10-10/55...
  ✅ Lote 10-10 concluído
  ⏳ Embeddings 11-11/55...
  ✅ Lote 11-11 concluído
  ⏳ Embeddings 12-12/55...
  ✅ Lote 12-12 concluído
  ⏳ Embeddings 13-13/55...
  ✅ Lote 13-13 concluído
  ⏳ Embeddings 14-14/55...
  ✅ Lote 14-14 concluído
  ⏳ Embeddings 15-15/55...
  ✅ Lote 15-15 concluído
  ⏳ Embeddings 16-16/55...
  ✅ Lote 16-16 concluído
  ⏳ Embeddings 17-17/55...
  ✅ Lote 17-17 concluído
  ⏳ Embeddings 18-18/55...
  ✅ Lote 18-18 concluído
  ⏳ Embeddings 19-19/55...
  ✅ Lote 19-19 concluído
  ⏳ Embeddings 20-20/55...
  ✅ Lote 20-20 concluído
  ⏳ Embeddings 21-21/55...
  ✅ Lote 21-21 concluído
  ⏳ Embeddings 22-22/55...
  ✅ Lote 22-22 concluído
  ⏳ Embeddings 23-23/55...
  ✅ Lote 23-23 concluído
  ⏳ Embeddings 24-24/55...
  ✅ Lote 24-24 concluído
  ⏳ Embeddings 25-25/55...
  ✅ Lote 25-25 concluído
  ⏳ Embeddings 26-26/55...
  ✅ Lote 26-26 concluído
  ⏳ Embeddings 27-27/55...
  ✅ Lote 27-27 concluído
  ⏳ Embeddings 28-28/55...
  ✅ Lote 28-28 concluído
  ⏳ Embeddings 29-29/55...
  ✅ Lote 29-29 concluído
  ⏳ Embeddings 30-30/55...
  ✅ Lote 30-30 concluído
  ⏳ Embeddings 31-31/55...
  ✅ Lote 31-31 concluído
  ⏳ Embeddings 32-32/55...
  ✅ Lote 32-32 concluído
  ⏳ Embeddings 33-33/55...
  ✅ Lote 33-33 concluído
  ⏳ Embeddings 34-34/55...
  ✅ Lote 34-34 concluído
  ⏳ Embeddings 35-35/55...
  ✅ Lote 35-35 concluído
  ⏳ Embeddings 36-36/55...
  ✅ Lote 36-36 concluído
  ⏳ Embeddings 37-37/55...
  ✅ Lote 37-37 concluído
  ⏳ Embeddings 38-38/55...
  ✅ Lote 38-38 concluído
  ⏳ Embeddings 39-39/55...
  ✅ Lote 39-39 concluído
  ⏳ Embeddings 40-40/55...
  ✅ Lote 40-40 concluído
  ⏳ Embeddings 41-41/55...
  ✅ Lote 41-41 concluído
  ⏳ Embeddings 42-42/55...
  ✅ Lote 42-42 concluído
  ⏳ Embeddings 43-43/55...
  ✅ Lote 43-43 concluído
  ⏳ Embeddings 44-44/55...
  ✅ Lote 44-44 concluído
  ⏳ Embeddings 45-45/55...
  ✅ Lote 45-45 concluído
  ⏳ Embeddings 46-46/55...
  ✅ Lote 46-46 concluído
  ⏳ Embeddings 47-47/55...
  ✅ Lote 47-47 concluído
  ⏳ Embeddings 48-48/55...
  ✅ Lote 48-48 concluído
  ⏳ Embeddings 49-49/55...
  ✅ Lote 49-49 concluído
  ⏳ Embeddings 50-50/55...
  ✅ Lote 50-50 concluído
  ⏳ Embeddings 51-51/55...
  ✅ Lote 51-51 concluído
  ⏳ Embeddings 52-52/55...
  ✅ Lote 52-52 concluído
  ⏳ Embeddings 53-53/55...
  ❌ ERRO no lote 53-53: Error code: 400 - {'error': {'message': 'HTTP 400: {"error":"Input length 8560 exceeds maximum allowed token size 8192"}', 'code': 400}}
Processamento interrompido para evitar perda de controle.
⚠️ Arquivo não salvo porque foram processados 52/55 chunks.

[14/36] Processando: results\gpt3_language_models\paragraph\chunks.json
Chunks: 593
  ⏳ Embeddings 1-1/593...
  ✅ Lote 1-1 concluído
  ⏳ Embeddings 2-2/593...
  ✅ Lote 2-2 concluído
  ⏳ Embeddings 3-3/593...
  ✅ Lote 3-3 concluído
  ⏳ Embeddings 4-4/593...
  ✅ Lote 4-4 concluído
  ⏳ Embeddings 5-5/593...
  ✅ Lote 5-5 concluído
  ⏳ Embeddings 6-6/593...
  ✅ Lote 6-6 concluído
  ⏳ Embeddings 7-7/593...
  ✅ Lote 7-7 concluído
  ⏳ Embeddings 8-8/593...
  ✅ Lote 8-8 concluído
  ⏳ Embeddings 9-9/593...
  ✅ Lote 9-9 concluído
  ⏳ Embeddings 10-10/593...
  ✅ Lote 10-10 concluído
  ⏳ Embeddings 11-11/593...
  ✅ Lote 11-11 concluído
  ⏳ Embeddings 12-12/593...
  ✅ Lote 12-12 concluído
  ⏳ Embeddings 13-13/593...
  ✅ Lote 13-13 concluído
  ⏳ Embeddings 14-14/593...
  ✅ Lote 14-14 concluído
  ⏳ Embeddings 15-15/593...
  ✅ Lote 15-15 concluído
  ⏳ Embeddings 16-16/593...
  ✅ Lote 16-16 concluído
  ⏳ Embeddings 17-17/593...
  ✅ Lote 17-17 concluído
  ⏳ Embeddings 18-18/593...
  ✅ Lote 18-18 concluído
  ⏳ Embeddings 19-19/593...
  ✅ Lote 19-19 concluído
  ⏳ Embeddings 20-20/593...
  ✅ Lote 20-20 concluído
  ⏳ Embeddings 21-21/593...
  ✅ Lote 21-21 concluído
  ⏳ Embeddings 22-22/593...
  ✅ Lote 22-22 concluído
  ⏳ Embeddings 23-23/593...
  ✅ Lote 23-23 concluído
  ⏳ Embeddings 24-24/593...
  ✅ Lote 24-24 concluído
  ⏳ Embeddings 25-25/593...
  ✅ Lote 25-25 concluído
  ⏳ Embeddings 26-26/593...
  ✅ Lote 26-26 concluído
  ⏳ Embeddings 27-27/593...
  ✅ Lote 27-27 concluído
  ⏳ Embeddings 28-28/593...
  ✅ Lote 28-28 concluído
  ⏳ Embeddings 29-29/593...
  ✅ Lote 29-29 concluído
  ⏳ Embeddings 30-30/593...
  ✅ Lote 30-30 concluído
  ⏳ Embeddings 31-31/593...
  ✅ Lote 31-31 concluído
  ⏳ Embeddings 32-32/593...
  ✅ Lote 32-32 concluído
  ⏳ Embeddings 33-33/593...
  ✅ Lote 33-33 concluído
  ⏳ Embeddings 34-34/593...
  ✅ Lote 34-34 concluído
  ⏳ Embeddings 35-35/593...
  ✅ Lote 35-35 concluído
  ⏳ Embeddings 36-36/593...
  ✅ Lote 36-36 concluído
  ⏳ Embeddings 37-37/593...
  ✅ Lote 37-37 concluído
  ⏳ Embeddings 38-38/593...
  ✅ Lote 38-38 concluído
  ⏳ Embeddings 39-39/593...
  ✅ Lote 39-39 concluído
  ⏳ Embeddings 40-40/593...
  ✅ Lote 40-40 concluído
  ⏳ Embeddings 41-41/593...
  ✅ Lote 41-41 concluído
  ⏳ Embeddings 42-42/593...
  ✅ Lote 42-42 concluído
  ⏳ Embeddings 43-43/593...
  ✅ Lote 43-43 concluído
  ⏳ Embeddings 44-44/593...
  ✅ Lote 44-44 concluído
  ⏳ Embeddings 45-45/593...
  ✅ Lote 45-45 concluído
  ⏳ Embeddings 46-46/593...
  ✅ Lote 46-46 concluído
  ⏳ Embeddings 47-47/593...
  ✅ Lote 47-47 concluído
  ⏳ Embeddings 48-48/593...
  ✅ Lote 48-48 concluído
  ⏳ Embeddings 49-49/593...
  ✅ Lote 49-49 concluído
  ⏳ Embeddings 50-50/593...
  ✅ Lote 50-50 concluído
  ⏳ Embeddings 51-51/593...
  ✅ Lote 51-51 concluído
  ⏳ Embeddings 52-52/593...
  ✅ Lote 52-52 concluído
  ⏳ Embeddings 53-53/593...
  ✅ Lote 53-53 concluído
  ⏳ Embeddings 54-54/593...
  ✅ Lote 54-54 concluído
  ⏳ Embeddings 55-55/593...
  ✅ Lote 55-55 concluído
  ⏳ Embeddings 56-56/593...
  ✅ Lote 56-56 concluído
  ⏳ Embeddings 57-57/593...
  ✅ Lote 57-57 concluído
  ⏳ Embeddings 58-58/593...
  ✅ Lote 58-58 concluído
  ⏳ Embeddings 59-59/593...
  ✅ Lote 59-59 concluído
  ⏳ Embeddings 60-60/593...
  ✅ Lote 60-60 concluído
  ⏳ Embeddings 61-61/593...
  ✅ Lote 61-61 concluído
  ⏳ Embeddings 62-62/593...
  ✅ Lote 62-62 concluído
  ⏳ Embeddings 63-63/593...
  ✅ Lote 63-63 concluído
  ⏳ Embeddings 64-64/593...
  ✅ Lote 64-64 concluído
  ⏳ Embeddings 65-65/593...
  ✅ Lote 65-65 concluído
  ⏳ Embeddings 66-66/593...
  ✅ Lote 66-66 concluído
  ⏳ Embeddings 67-67/593...
  ✅ Lote 67-67 concluído
  ⏳ Embeddings 68-68/593...
  ✅ Lote 68-68 concluído
  ⏳ Embeddings 69-69/593...
  ✅ Lote 69-69 concluído
  ⏳ Embeddings 70-70/593...
  ✅ Lote 70-70 concluído
  ⏳ Embeddings 71-71/593...
  ✅ Lote 71-71 concluído
  ⏳ Embeddings 72-72/593...
  ✅ Lote 72-72 concluído
  ⏳ Embeddings 73-73/593...
  ✅ Lote 73-73 concluído
  ⏳ Embeddings 74-74/593...
  ✅ Lote 74-74 concluído
  ⏳ Embeddings 75-75/593...
  ✅ Lote 75-75 concluído
  ⏳ Embeddings 76-76/593...
  ✅ Lote 76-76 concluído
  ⏳ Embeddings 77-77/593...
  ✅ Lote 77-77 concluído
  ⏳ Embeddings 78-78/593...
  ✅ Lote 78-78 concluído
  ⏳ Embeddings 79-79/593...
  ✅ Lote 79-79 concluído
  ⏳ Embeddings 80-80/593...
  ✅ Lote 80-80 concluído
  ⏳ Embeddings 81-81/593...
  ✅ Lote 81-81 concluído
  ⏳ Embeddings 82-82/593...
  ✅ Lote 82-82 concluído
  ⏳ Embeddings 83-83/593...
  ✅ Lote 83-83 concluído
  ⏳ Embeddings 84-84/593...
  ✅ Lote 84-84 concluído
  ⏳ Embeddings 85-85/593...
  ✅ Lote 85-85 concluído
  ⏳ Embeddings 86-86/593...
  ✅ Lote 86-86 concluído
  ⏳ Embeddings 87-87/593...
  ✅ Lote 87-87 concluído
  ⏳ Embeddings 88-88/593...
  ✅ Lote 88-88 concluído
  ⏳ Embeddings 89-89/593...
  ✅ Lote 89-89 concluído
  ⏳ Embeddings 90-90/593...
  ✅ Lote 90-90 concluído
  ⏳ Embeddings 91-91/593...
  ✅ Lote 91-91 concluído
  ⏳ Embeddings 92-92/593...
  ✅ Lote 92-92 concluído
  ⏳ Embeddings 93-93/593...
  ✅ Lote 93-93 concluído
  ⏳ Embeddings 94-94/593...
  ✅ Lote 94-94 concluído
  ⏳ Embeddings 95-95/593...
  ✅ Lote 95-95 concluído
  ⏳ Embeddings 96-96/593...
  ✅ Lote 96-96 concluído
  ⏳ Embeddings 97-97/593...
  ✅ Lote 97-97 concluído
  ⏳ Embeddings 98-98/593...
  ✅ Lote 98-98 concluído
  ⏳ Embeddings 99-99/593...
  ✅ Lote 99-99 concluído
  ⏳ Embeddings 100-100/593...
  ✅ Lote 100-100 concluído
  ⏳ Embeddings 101-101/593...
  ✅ Lote 101-101 concluído
  ⏳ Embeddings 102-102/593...
  ✅ Lote 102-102 concluído
  ⏳ Embeddings 103-103/593...
  ✅ Lote 103-103 concluído
  ⏳ Embeddings 104-104/593...
  ✅ Lote 104-104 concluído
  ⏳ Embeddings 105-105/593...
  ✅ Lote 105-105 concluído
  ⏳ Embeddings 106-106/593...
  ✅ Lote 106-106 concluído
  ⏳ Embeddings 107-107/593...
  ✅ Lote 107-107 concluído
  ⏳ Embeddings 108-108/593...
  ✅ Lote 108-108 concluído
  ⏳ Embeddings 109-109/593...
  ✅ Lote 109-109 concluído
  ⏳ Embeddings 110-110/593...
  ✅ Lote 110-110 concluído
  ⏳ Embeddings 111-111/593...
  ✅ Lote 111-111 concluído
  ⏳ Embeddings 112-112/593...
  ✅ Lote 112-112 concluído
  ⏳ Embeddings 113-113/593...
  ✅ Lote 113-113 concluído
  ⏳ Embeddings 114-114/593...
  ✅ Lote 114-114 concluído
  ⏳ Embeddings 115-115/593...
  ✅ Lote 115-115 concluído
  ⏳ Embeddings 116-116/593...
  ✅ Lote 116-116 concluído
  ⏳ Embeddings 117-117/593...
  ✅ Lote 117-117 concluído
  ⏳ Embeddings 118-118/593...
  ✅ Lote 118-118 concluído
  ⏳ Embeddings 119-119/593...
  ✅ Lote 119-119 concluído
  ⏳ Embeddings 120-120/593...
  ✅ Lote 120-120 concluído
  ⏳ Embeddings 121-121/593...
  ✅ Lote 121-121 concluído
  ⏳ Embeddings 122-122/593...
  ✅ Lote 122-122 concluído
  ⏳ Embeddings 123-123/593...
  ✅ Lote 123-123 concluído
  ⏳ Embeddings 124-124/593...
  ✅ Lote 124-124 concluído
  ⏳ Embeddings 125-125/593...
  ✅ Lote 125-125 concluído
  ⏳ Embeddings 126-126/593...
  ✅ Lote 126-126 concluído
  ⏳ Embeddings 127-127/593...
  ✅ Lote 127-127 concluído
  ⏳ Embeddings 128-128/593...
  ✅ Lote 128-128 concluído
  ⏳ Embeddings 129-129/593...
  ✅ Lote 129-129 concluído
  ⏳ Embeddings 130-130/593...
  ✅ Lote 130-130 concluído
  ⏳ Embeddings 131-131/593...
  ✅ Lote 131-131 concluído
  ⏳ Embeddings 132-132/593...
  ✅ Lote 132-132 concluído
  ⏳ Embeddings 133-133/593...
  ✅ Lote 133-133 concluído
  ⏳ Embeddings 134-134/593...
  ✅ Lote 134-134 concluído
  ⏳ Embeddings 135-135/593...
  ✅ Lote 135-135 concluído
  ⏳ Embeddings 136-136/593...
  ✅ Lote 136-136 concluído
  ⏳ Embeddings 137-137/593...
  ✅ Lote 137-137 concluído
  ⏳ Embeddings 138-138/593...
  ✅ Lote 138-138 concluído
  ⏳ Embeddings 139-139/593...
  ✅ Lote 139-139 concluído
  ⏳ Embeddings 140-140/593...
  ✅ Lote 140-140 concluído
  ⏳ Embeddings 141-141/593...
  ✅ Lote 141-141 concluído
  ⏳ Embeddings 142-142/593...
  ✅ Lote 142-142 concluído
  ⏳ Embeddings 143-143/593...
  ✅ Lote 143-143 concluído
  ⏳ Embeddings 144-144/593...
  ✅ Lote 144-144 concluído
  ⏳ Embeddings 145-145/593...
  ✅ Lote 145-145 concluído
  ⏳ Embeddings 146-146/593...
  ✅ Lote 146-146 concluído
  ⏳ Embeddings 147-147/593...
  ✅ Lote 147-147 concluído
  ⏳ Embeddings 148-148/593...
  ✅ Lote 148-148 concluído
  ⏳ Embeddings 149-149/593...
  ✅ Lote 149-149 concluído
  ⏳ Embeddings 150-150/593...
  ✅ Lote 150-150 concluído
  ⏳ Embeddings 151-151/593...
  ✅ Lote 151-151 concluído
  ⏳ Embeddings 152-152/593...
  ✅ Lote 152-152 concluído
  ⏳ Embeddings 153-153/593...
  ✅ Lote 153-153 concluído
  ⏳ Embeddings 154-154/593...
  ✅ Lote 154-154 concluído
  ⏳ Embeddings 155-155/593...
  ✅ Lote 155-155 concluído
  ⏳ Embeddings 156-156/593...
  ✅ Lote 156-156 concluído
  ⏳ Embeddings 157-157/593...
  ✅ Lote 157-157 concluído
  ⏳ Embeddings 158-158/593...
  ✅ Lote 158-158 concluído
  ⏳ Embeddings 159-159/593...
  ✅ Lote 159-159 concluído
  ⏳ Embeddings 160-160/593...
  ✅ Lote 160-160 concluído
  ⏳ Embeddings 161-161/593...
  ✅ Lote 161-161 concluído
  ⏳ Embeddings 162-162/593...
  ✅ Lote 162-162 concluído
  ⏳ Embeddings 163-163/593...
  ✅ Lote 163-163 concluído
  ⏳ Embeddings 164-164/593...
  ✅ Lote 164-164 concluído
  ⏳ Embeddings 165-165/593...
  ✅ Lote 165-165 concluído
  ⏳ Embeddings 166-166/593...
  ✅ Lote 166-166 concluído
  ⏳ Embeddings 167-167/593...
  ✅ Lote 167-167 concluído
  ⏳ Embeddings 168-168/593...
  ✅ Lote 168-168 concluído
  ⏳ Embeddings 169-169/593...
  ✅ Lote 169-169 concluído
  ⏳ Embeddings 170-170/593...
  ✅ Lote 170-170 concluído
  ⏳ Embeddings 171-171/593...
  ✅ Lote 171-171 concluído
  ⏳ Embeddings 172-172/593...
  ✅ Lote 172-172 concluído
  ⏳ Embeddings 173-173/593...
  ✅ Lote 173-173 concluído
  ⏳ Embeddings 174-174/593...
  ✅ Lote 174-174 concluído
  ⏳ Embeddings 175-175/593...
  ✅ Lote 175-175 concluído
  ⏳ Embeddings 176-176/593...
  ✅ Lote 176-176 concluído
  ⏳ Embeddings 177-177/593...
  ✅ Lote 177-177 concluído
  ⏳ Embeddings 178-178/593...
  ✅ Lote 178-178 concluído
  ⏳ Embeddings 179-179/593...
  ✅ Lote 179-179 concluído
  ⏳ Embeddings 180-180/593...
  ✅ Lote 180-180 concluído
  ⏳ Embeddings 181-181/593...
  ✅ Lote 181-181 concluído
  ⏳ Embeddings 182-182/593...
  ✅ Lote 182-182 concluído
  ⏳ Embeddings 183-183/593...
  ✅ Lote 183-183 concluído
  ⏳ Embeddings 184-184/593...
  ✅ Lote 184-184 concluído
  ⏳ Embeddings 185-185/593...
  ✅ Lote 185-185 concluído
  ⏳ Embeddings 186-186/593...
  ✅ Lote 186-186 concluído
  ⏳ Embeddings 187-187/593...
  ✅ Lote 187-187 concluído
  ⏳ Embeddings 188-188/593...
  ✅ Lote 188-188 concluído
  ⏳ Embeddings 189-189/593...
  ✅ Lote 189-189 concluído
  ⏳ Embeddings 190-190/593...
  ✅ Lote 190-190 concluído
  ⏳ Embeddings 191-191/593...
  ✅ Lote 191-191 concluído
  ⏳ Embeddings 192-192/593...
  ✅ Lote 192-192 concluído
  ⏳ Embeddings 193-193/593...
  ✅ Lote 193-193 concluído
  ⏳ Embeddings 194-194/593...
  ✅ Lote 194-194 concluído
  ⏳ Embeddings 195-195/593...
  ✅ Lote 195-195 concluído
  ⏳ Embeddings 196-196/593...
  ✅ Lote 196-196 concluído
  ⏳ Embeddings 197-197/593...
  ✅ Lote 197-197 concluído
  ⏳ Embeddings 198-198/593...
  ✅ Lote 198-198 concluído
  ⏳ Embeddings 199-199/593...
  ✅ Lote 199-199 concluído
  ⏳ Embeddings 200-200/593...
  ✅ Lote 200-200 concluído
  ⏳ Embeddings 201-201/593...
  ✅ Lote 201-201 concluído
  ⏳ Embeddings 202-202/593...
  ✅ Lote 202-202 concluído
  ⏳ Embeddings 203-203/593...
  ✅ Lote 203-203 concluído
  ⏳ Embeddings 204-204/593...
  ✅ Lote 204-204 concluído
  ⏳ Embeddings 205-205/593...
  ✅ Lote 205-205 concluído
  ⏳ Embeddings 206-206/593...
  ✅ Lote 206-206 concluído
  ⏳ Embeddings 207-207/593...
  ✅ Lote 207-207 concluído
  ⏳ Embeddings 208-208/593...
  ✅ Lote 208-208 concluído
  ⏳ Embeddings 209-209/593...
  ✅ Lote 209-209 concluído
  ⏳ Embeddings 210-210/593...
  ✅ Lote 210-210 concluído
  ⏳ Embeddings 211-211/593...
  ✅ Lote 211-211 concluído
  ⏳ Embeddings 212-212/593...
  ✅ Lote 212-212 concluído
  ⏳ Embeddings 213-213/593...
  ✅ Lote 213-213 concluído
  ⏳ Embeddings 214-214/593...
  ✅ Lote 214-214 concluído
  ⏳ Embeddings 215-215/593...
  ✅ Lote 215-215 concluído
  ⏳ Embeddings 216-216/593...
  ✅ Lote 216-216 concluído
  ⏳ Embeddings 217-217/593...
  ✅ Lote 217-217 concluído
  ⏳ Embeddings 218-218/593...
  ✅ Lote 218-218 concluído
  ⏳ Embeddings 219-219/593...
  ✅ Lote 219-219 concluído
  ⏳ Embeddings 220-220/593...
  ✅ Lote 220-220 concluído
  ⏳ Embeddings 221-221/593...
  ✅ Lote 221-221 concluído
  ⏳ Embeddings 222-222/593...
  ✅ Lote 222-222 concluído
  ⏳ Embeddings 223-223/593...
  ✅ Lote 223-223 concluído
  ⏳ Embeddings 224-224/593...
  ✅ Lote 224-224 concluído
  ⏳ Embeddings 225-225/593...
  ✅ Lote 225-225 concluído
  ⏳ Embeddings 226-226/593...
  ✅ Lote 226-226 concluído
  ⏳ Embeddings 227-227/593...
  ✅ Lote 227-227 concluído
  ⏳ Embeddings 228-228/593...
  ✅ Lote 228-228 concluído
  ⏳ Embeddings 229-229/593...
  ✅ Lote 229-229 concluído
  ⏳ Embeddings 230-230/593...
  ✅ Lote 230-230 concluído
  ⏳ Embeddings 231-231/593...
  ✅ Lote 231-231 concluído
  ⏳ Embeddings 232-232/593...
  ✅ Lote 232-232 concluído
  ⏳ Embeddings 233-233/593...
  ✅ Lote 233-233 concluído
  ⏳ Embeddings 234-234/593...
  ✅ Lote 234-234 concluído
  ⏳ Embeddings 235-235/593...
  ✅ Lote 235-235 concluído
  ⏳ Embeddings 236-236/593...
  ✅ Lote 236-236 concluído
  ⏳ Embeddings 237-237/593...
  ✅ Lote 237-237 concluído
  ⏳ Embeddings 238-238/593...
  ✅ Lote 238-238 concluído
  ⏳ Embeddings 239-239/593...
  ✅ Lote 239-239 concluído
  ⏳ Embeddings 240-240/593...
  ✅ Lote 240-240 concluído
  ⏳ Embeddings 241-241/593...
  ✅ Lote 241-241 concluído
  ⏳ Embeddings 242-242/593...
  ✅ Lote 242-242 concluído
  ⏳ Embeddings 243-243/593...
  ✅ Lote 243-243 concluído
  ⏳ Embeddings 244-244/593...
  ✅ Lote 244-244 concluído
  ⏳ Embeddings 245-245/593...
  ✅ Lote 245-245 concluído
  ⏳ Embeddings 246-246/593...
  ✅ Lote 246-246 concluído
  ⏳ Embeddings 247-247/593...
  ✅ Lote 247-247 concluído
  ⏳ Embeddings 248-248/593...
  ✅ Lote 248-248 concluído
  ⏳ Embeddings 249-249/593...
  ✅ Lote 249-249 concluído
  ⏳ Embeddings 250-250/593...
  ✅ Lote 250-250 concluído
  ⏳ Embeddings 251-251/593...
  ✅ Lote 251-251 concluído
  ⏳ Embeddings 252-252/593...
  ✅ Lote 252-252 concluído
  ⏳ Embeddings 253-253/593...
  ✅ Lote 253-253 concluído
  ⏳ Embeddings 254-254/593...
  ✅ Lote 254-254 concluído
  ⏳ Embeddings 255-255/593...
  ✅ Lote 255-255 concluído
  ⏳ Embeddings 256-256/593...
  ✅ Lote 256-256 concluído
  ⏳ Embeddings 257-257/593...
  ✅ Lote 257-257 concluído
  ⏳ Embeddings 258-258/593...
  ✅ Lote 258-258 concluído
  ⏳ Embeddings 259-259/593...
  ✅ Lote 259-259 concluído
  ⏳ Embeddings 260-260/593...
  ✅ Lote 260-260 concluído
  ⏳ Embeddings 261-261/593...
  ✅ Lote 261-261 concluído
  ⏳ Embeddings 262-262/593...
  ✅ Lote 262-262 concluído
  ⏳ Embeddings 263-263/593...
  ✅ Lote 263-263 concluído
  ⏳ Embeddings 264-264/593...
  ✅ Lote 264-264 concluído
  ⏳ Embeddings 265-265/593...
  ✅ Lote 265-265 concluído
  ⏳ Embeddings 266-266/593...
  ✅ Lote 266-266 concluído
  ⏳ Embeddings 267-267/593...
  ✅ Lote 267-267 concluído
  ⏳ Embeddings 268-268/593...
  ✅ Lote 268-268 concluído
  ⏳ Embeddings 269-269/593...
  ✅ Lote 269-269 concluído
  ⏳ Embeddings 270-270/593...
  ✅ Lote 270-270 concluído
  ⏳ Embeddings 271-271/593...
  ✅ Lote 271-271 concluído
  ⏳ Embeddings 272-272/593...
  ✅ Lote 272-272 concluído
  ⏳ Embeddings 273-273/593...
  ✅ Lote 273-273 concluído
  ⏳ Embeddings 274-274/593...
  ✅ Lote 274-274 concluído
  ⏳ Embeddings 275-275/593...
  ✅ Lote 275-275 concluído
  ⏳ Embeddings 276-276/593...
  ✅ Lote 276-276 concluído
  ⏳ Embeddings 277-277/593...
  ✅ Lote 277-277 concluído
  ⏳ Embeddings 278-278/593...
  ✅ Lote 278-278 concluído
  ⏳ Embeddings 279-279/593...
  ✅ Lote 279-279 concluído
  ⏳ Embeddings 280-280/593...
  ✅ Lote 280-280 concluído
  ⏳ Embeddings 281-281/593...
  ✅ Lote 281-281 concluído
  ⏳ Embeddings 282-282/593...
  ✅ Lote 282-282 concluído
  ⏳ Embeddings 283-283/593...
  ✅ Lote 283-283 concluído
  ⏳ Embeddings 284-284/593...
  ✅ Lote 284-284 concluído
  ⏳ Embeddings 285-285/593...
  ✅ Lote 285-285 concluído
  ⏳ Embeddings 286-286/593...
  ✅ Lote 286-286 concluído
  ⏳ Embeddings 287-287/593...
  ✅ Lote 287-287 concluído
  ⏳ Embeddings 288-288/593...
  ✅ Lote 288-288 concluído
  ⏳ Embeddings 289-289/593...
  ✅ Lote 289-289 concluído
  ⏳ Embeddings 290-290/593...
  ✅ Lote 290-290 concluído
  ⏳ Embeddings 291-291/593...
  ✅ Lote 291-291 concluído
  ⏳ Embeddings 292-292/593...
  ✅ Lote 292-292 concluído
  ⏳ Embeddings 293-293/593...
  ✅ Lote 293-293 concluído
  ⏳ Embeddings 294-294/593...
  ✅ Lote 294-294 concluído
  ⏳ Embeddings 295-295/593...
  ✅ Lote 295-295 concluído
  ⏳ Embeddings 296-296/593...
  ✅ Lote 296-296 concluído
  ⏳ Embeddings 297-297/593...
  ✅ Lote 297-297 concluído
  ⏳ Embeddings 298-298/593...
  ✅ Lote 298-298 concluído
  ⏳ Embeddings 299-299/593...
  ✅ Lote 299-299 concluído
  ⏳ Embeddings 300-300/593...
  ✅ Lote 300-300 concluído
  ⏳ Embeddings 301-301/593...
  ✅ Lote 301-301 concluído
  ⏳ Embeddings 302-302/593...
  ✅ Lote 302-302 concluído
  ⏳ Embeddings 303-303/593...
  ✅ Lote 303-303 concluído
  ⏳ Embeddings 304-304/593...
  ✅ Lote 304-304 concluído
  ⏳ Embeddings 305-305/593...
  ✅ Lote 305-305 concluído

In [32]:
import json
from pathlib import Path

# Arquivo que apresentou o primeiro problema
arquivo = Path("results/gpt3_language_models/markdown/chunks.json")

with open(arquivo, "r", encoding="utf-8") as f:
    chunks = json.load(f)

# O erro mostrou "53-53".
# Como Python começa em 0, o chunk 53 está no índice 52.
chunk_problematico = chunks[52]

texto = chunk_problematico["text"]

print("Chunk:", 53)
print("Quantidade de caracteres:", len(texto))
print("\nINÍCIO DO CHUNK:")
print("=" * 70)
print(texto[:2000])
print("=" * 70)

Chunk: 53
Quantidade de caracteres: 46447

INÍCIO DO CHUNK:
======================================================================
The following figures illustrate the formatting and phrasing of all the tasks included in the paper. All data comes from the ground truth datasets in this section, and no samples from GPT-3 are included here.
| Context  →  Article:  Informal  conversation  is  an  important  part  of  any  business  relationship.Before  you  start  a  discussion,however,make  sure  you  understand  which  topics  are  suitable  and  which  are  considered  taboo  in  a  particular  culture.  Latin  Americans  enjoy  sharing  information  about  their  local  history,  art  and  customs.You  may  expect  questions  about  your  family,and  be  sure  to  show  pictures  of  your  children.You  may  feel  free  to  ask  similar  questions  of  your  Latin  American  friends.The  French  think  of  conversation  as  an  art  form,and  they  enjoy  the  value  of  lively  discussions  as  well  as  disagreements.  For  them,arguments  can  be  interesting  and  they  can  cover  pretty  much  or  any  topic  ----  as  long  as  they  occur  in  are  respectful  and  intelligent  manner.  In  the  United  States,business  people  like  to  discuss  a  wide  range  of  topics,including  opinions  about  work,family,hobbies,and  politics.  In  Japan,China,and  Korea,however,people  are  much  more  private.They  do  not  share  much  about  their  thoughts,feelings,or  emotions  because  they  feel  that  doing  so  might  take  away  from  the  harmonious  business  relationship  they're  trying  to  build.Middle  Easterners  are  also  private  about  their  personal  lives  and  family  matters.It  is  considered  rude,for  example,to  ask  a  businessman  from  Saudi  Arabia  about  his  wife  or  children.  As  a  general  rule,it's  best  not  to  talk  about  politics  or  religion  with  your  business  friends.This  can  get  you  into  trouble,even  in  the  United  States,where  people  hold  different  religious  views.In  addition,discussing  one's  salary  is  usually  consi
======================================================================

In [34]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
import json
from pathlib import Path

splitter_secundario = RecursiveCharacterTextSplitter(
    chunk_size=6000,
    chunk_overlap=300,
    separators=["\n\n", "\n", " ", ""],
    length_function=len
)

arquivo = Path(
    "results/gpt3_language_models/markdown/chunks.json"
)

with open(arquivo, "r", encoding="utf-8") as f:
    chunks = json.load(f)

chunks_corrigidos = []

for item in chunks:
    texto = item["text"]

    # Agora divide qualquer chunk acima de 6000 caracteres
    if len(texto) > 6000:

        subchunks = splitter_secundario.split_text(texto)

        for i, subchunk in enumerate(subchunks, start=1):

            novo_item = item.copy()

            novo_item["chunk_id"] = (
                f"{item['chunk_id']}_sub{i:02d}"
            )

            novo_item["text"] = subchunk

            novo_item["metadata"] = {
                **item.get("metadata", {}),
                "subdividido": True
            }

            chunks_corrigidos.append(novo_item)

    else:
        chunks_corrigidos.append(item)

print("Chunks originais:", len(chunks))
print("Chunks após correção:", len(chunks_corrigidos))
print(
    "Maior chunk após correção:",
    max(len(x["text"]) for x in chunks_corrigidos)
)

Chunks originais: 55
Chunks após correção: 88
Maior chunk após correção: 5999

In [35]:
arquivo_corrigido = Path(
    "results/gpt3_language_models/markdown/chunks_corrigidos.json"
)

with open(arquivo_corrigido, "w", encoding="utf-8") as f:
    json.dump(
        chunks_corrigidos,
        f,
        ensure_ascii=False,
        indent=2
    )

print("✅ Arquivo corrigido salvo!")

✅ Arquivo corrigido salvo!

In [36]:
import json
from pathlib import Path

arquivo_corrigido = Path(
    "results/gpt3_language_models/markdown/chunks_corrigidos.json"
)

with open(arquivo_corrigido, "r", encoding="utf-8") as f:
    chunks_corrigidos = json.load(f)

print("Total de chunks corrigidos:", len(chunks_corrigidos))
print(
    "Maior tamanho:",
    max(len(item["text"]) for item in chunks_corrigidos)
)

# Teste apenas dos primeiros 5
textos_teste = [
    item["text"]
    for item in chunks_corrigidos[:5]
]

embeddings_teste = get_embeddings_batch(textos_teste)

print("Textos enviados:", len(textos_teste))
print("Embeddings recebidos:", len(embeddings_teste))
print("Dimensão:", len(embeddings_teste[0]))

Total de chunks corrigidos: 88
Maior tamanho: 5999
Textos enviados: 5
Embeddings recebidos: 5
Dimensão: 2048

In [37]:
import json
from pathlib import Path
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter_secundario = RecursiveCharacterTextSplitter(
    chunk_size=6000,
    chunk_overlap=300,
    separators=["\n\n", "\n", " ", ""],
    length_function=len
)

arquivos_problematicos = [
    Path("results/gpt3_language_models/paragraph/chunks.json"),
    Path("results/gpt4_technical_report/markdown/chunks.json"),
]

for arquivo in arquivos_problematicos:

    print("=" * 70)
    print("Processando:", arquivo)

    with open(arquivo, "r", encoding="utf-8") as f:
        chunks = json.load(f)

    chunks_corrigidos = []

    for item in chunks:
        texto = item["text"]

        if len(texto) > 6000:

            subchunks = splitter_secundario.split_text(texto)

            for i, subchunk in enumerate(subchunks, start=1):

                novo_item = item.copy()

                novo_item["chunk_id"] = (
                    f"{item['chunk_id']}_sub{i:02d}"
                )

                novo_item["text"] = subchunk

                novo_item["metadata"] = {
                    **item.get("metadata", {}),
                    "subdividido": True
                }

                chunks_corrigidos.append(novo_item)

        else:
            chunks_corrigidos.append(item)

    arquivo_saida = (
        arquivo.parent
        / "chunks_corrigidos.json"
    )

    with open(
        arquivo_saida,
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            chunks_corrigidos,
            f,
            ensure_ascii=False,
            indent=2
        )

    print("Chunks originais:", len(chunks))
    print("Chunks corrigidos:", len(chunks_corrigidos))
    print(
        "Maior chunk:",
        max(len(x["text"]) for x in chunks_corrigidos)
    )
    print("✅ Salvo:", arquivo_saida)

======================================================================
Processando: results\gpt3_language_models\paragraph\chunks.json
Chunks originais: 593
Chunks corrigidos: 599
Maior chunk: 5999
✅ Salvo: results\gpt3_language_models\paragraph\chunks_corrigidos.json
======================================================================
Processando: results\gpt4_technical_report\markdown\chunks.json
Chunks originais: 195
Chunks corrigidos: 211
Maior chunk: 5999
✅ Salvo: results\gpt4_technical_report\markdown\chunks_corrigidos.json

In [38]:
import json
import time
from pathlib import Path

arquivos_corrigidos = [
    Path("results/gpt3_language_models/markdown/chunks_corrigidos.json"),
    Path("results/gpt3_language_models/paragraph/chunks_corrigidos.json"),
    Path("results/gpt4_technical_report/markdown/chunks_corrigidos.json"),
]

# Como já tivemos problema de limite, vamos usar lotes pequenos
TAMANHO_LOTE = 5
PAUSA_ENTRE_LOTES = 0.5

print("=" * 70)
print("GERANDO EMBEDDINGS DOS ARQUIVOS CORRIGIDOS")
print("=" * 70)

for numero, arquivo in enumerate(arquivos_corrigidos, start=1):

    print(f"\n[{numero}/{len(arquivos_corrigidos)}]")
    print("Arquivo:", arquivo)

    with open(arquivo, "r", encoding="utf-8") as f:
        chunks = json.load(f)

    total = len(chunks)
    resultados = []

    print("Total de chunks:", total)

    for inicio in range(0, total, TAMANHO_LOTE):

        fim = min(
            inicio + TAMANHO_LOTE,
            total
        )

        lote = chunks[inicio:fim]

        textos = [
            item["text"]
            for item in lote
        ]

        print(
            f"  ⏳ Embeddings {inicio + 1}-{fim}/{total}...",
            flush=True
        )

        try:

            embeddings = get_embeddings_batch(textos)

            for item, embedding in zip(lote, embeddings):

                novo_item = item.copy()

                novo_item["embedding"] = embedding

                resultados.append(novo_item)

            print(
                f"  ✅ {inicio + 1}-{fim} concluído",
                flush=True
            )

            time.sleep(PAUSA_ENTRE_LOTES)

        except Exception as erro:

            print(
                f"  ❌ ERRO em {inicio + 1}-{fim}: {erro}"
            )

            break

    # Salva somente se TODOS forem processados
    if len(resultados) == total:

        arquivo_saida = (
            arquivo.parent
            / "chunks_embeddings.json"
        )

        with open(
            arquivo_saida,
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(
                resultados,
                f,
                ensure_ascii=False,
                indent=2
            )

        print(
            f"  💾 Salvo: {arquivo_saida}"
        )

    else:

        print(
            f"  ⚠️ Incompleto: "
            f"{len(resultados)}/{total}"
        )

print("\n" + "=" * 70)
print("🎉 PROCESSAMENTO DOS CORRIGIDOS FINALIZADO")

======================================================================
GERANDO EMBEDDINGS DOS ARQUIVOS CORRIGIDOS
======================================================================

[1/3]
Arquivo: results\gpt3_language_models\markdown\chunks_corrigidos.json
Total de chunks: 88
  ⏳ Embeddings 1-5/88...
  ✅ 1-5 concluído
  ⏳ Embeddings 6-10/88...
  ✅ 6-10 concluído
  ⏳ Embeddings 11-15/88...
  ✅ 11-15 concluído
  ⏳ Embeddings 16-20/88...
  ✅ 16-20 concluído
  ⏳ Embeddings 21-25/88...
  ✅ 21-25 concluído
  ⏳ Embeddings 26-30/88...
  ✅ 26-30 concluído
  ⏳ Embeddings 31-35/88...
  ✅ 31-35 concluído
  ⏳ Embeddings 36-40/88...
  ✅ 36-40 concluído
  ⏳ Embeddings 41-45/88...
  ✅ 41-45 concluído
  ⏳ Embeddings 46-50/88...
  ✅ 46-50 concluído
  ⏳ Embeddings 51-55/88...
  ✅ 51-55 concluído
  ⏳ Embeddings 56-60/88...
  ✅ 56-60 concluído
  ⏳ Embeddings 61-65/88...
  ✅ 61-65 concluído
  ⏳ Embeddings 66-70/88...
  ✅ 66-70 concluído
  ⏳ Embeddings 71-75/88...
  ✅ 71-75 concluído
  ⏳ Embeddings 76-80/88...
  ✅ 76-80 concluído
  ⏳ Embeddings 81-85/88...
  ✅ 81-85 concluído
  ⏳ Embeddings 86-88/88...
  ✅ 86-88 concluído
  💾 Salvo: results\gpt3_language_models\markdown\chunks_embeddings.json

[2/3]
Arquivo: results\gpt3_language_models\paragraph\chunks_corrigidos.json
Total de chunks: 599
  ⏳ Embeddings 1-5/599...
  ✅ 1-5 concluído
  ⏳ Embeddings 6-10/599...
  ✅ 6-10 concluído
  ⏳ Embeddings 11-15/599...
  ✅ 11-15 concluído
  ⏳ Embeddings 16-20/599...
  ✅ 16-20 concluído
  ⏳ Embeddings 21-25/599...
  ✅ 21-25 concluído
  ⏳ Embeddings 26-30/599...
  ✅ 26-30 concluído
  ⏳ Embeddings 31-35/599...
  ✅ 31-35 concluído
  ⏳ Embeddings 36-40/599...
  ✅ 36-40 concluído
  ⏳ Embeddings 41-45/599...
  ✅ 41-45 concluído
  ⏳ Embeddings 46-50/599...
  ✅ 46-50 concluído
  ⏳ Embeddings 51-55/599...
  ✅ 51-55 concluído
  ⏳ Embeddings 56-60/599...
  ✅ 56-60 concluído
  ⏳ Embeddings 61-65/599...
  ✅ 61-65 concluído
  ⏳ Embeddings 66-70/599...
  ✅ 66-70 concluído
  ⏳ Embeddings 71-75/599...
  ✅ 71-75 concluído
  ⏳ Embeddings 76-80/599...
  ✅ 76-80 concluído
  ⏳ Embeddings 81-85/599...
  ✅ 81-85 concluído
  ⏳ Embeddings 86-90/599...
  ✅ 86-90 concluído
  ⏳ Embeddings 91-95/599...
  ✅ 91-95 concluído
  ⏳ Embeddings 96-100/599...
  ✅ 96-100 concluído
  ⏳ Embeddings 101-105/599...
  ✅ 101-105 concluído
  ⏳ Embeddings 106-110/599...
  ✅ 106-110 concluído
  ⏳ Embeddings 111-115/599...
  ✅ 111-115 concluído
  ⏳ Embeddings 116-120/599...
  ✅ 116-120 concluído
  ⏳ Embeddings 121-125/599...
  ✅ 121-125 concluído
  ⏳ Embeddings 126-130/599...
  ✅ 126-130 concluído
  ⏳ Embeddings 131-135/599...
  ✅ 131-135 concluído
  ⏳ Embeddings 136-140/599...
  ✅ 136-140 concluído
  ⏳ Embeddings 141-145/599...
  ✅ 141-145 concluído
  ⏳ Embeddings 146-150/599...
  ✅ 146-150 concluído
  ⏳ Embeddings 151-155/599...
  ✅ 151-155 concluído
  ⏳ Embeddings 156-160/599...
  ✅ 156-160 concluído
  ⏳ Embeddings 161-165/599...
  ✅ 161-165 concluído
  ⏳ Embeddings 166-170/599...
  ✅ 166-170 concluído
  ⏳ Embeddings 171-175/599...
  ✅ 171-175 concluído
  ⏳ Embeddings 176-180/599...
  ✅ 176-180 concluído
  ⏳ Embeddings 181-185/599...
  ✅ 181-185 concluído
  ⏳ Embeddings 186-190/599...
  ✅ 186-190 concluído
  ⏳ Embeddings 191-195/599...
  ✅ 191-195 concluído
  ⏳ Embeddings 196-200/599...
  ✅ 196-200 concluído
  ⏳ Embeddings 201-205/599...
  ✅ 201-205 concluído
  ⏳ Embeddings 206-210/599...
  ✅ 206-210 concluído
  ⏳ Embeddings 211-215/599...
  ✅ 211-215 concluído
  ⏳ Embeddings 216-220/599...
  ✅ 216-220 concluído
  ⏳ Embeddings 221-225/599...
  ✅ 221-225 concluído
  ⏳ Embeddings 226-230/599...
  ✅ 226-230 concluído
  ⏳ Embeddings 231-235/599...
  ✅ 231-235 concluído
  ⏳ Embeddings 236-240/599...
  ✅ 236-240 concluído
  ⏳ Embeddings 241-245/599...
  ✅ 241-245 concluído
  ⏳ Embeddings 246-250/599...
  ✅ 246-250 concluído
  ⏳ Embeddings 251-255/599...
  ✅ 251-255 concluído
  ⏳ Embeddings 256-260/599...
  ✅ 256-260 concluído
  ⏳ Embeddings 261-265/599...
  ✅ 261-265 concluído
  ⏳ Embeddings 266-270/599...
  ✅ 266-270 concluído
  ⏳ Embeddings 271-275/599...
  ✅ 271-275 concluído
  ⏳ Embeddings 276-280/599...
  ✅ 276-280 concluído
  ⏳ Embeddings 281-285/599...
  ✅ 281-285 concluído
  ⏳ Embeddings 286-290/599...
  ✅ 286-290 concluído
  ⏳ Embeddings 291-295/599...
  ✅ 291-295 concluído
  ⏳ Embeddings 296-300/599...
  ✅ 296-300 concluído
  ⏳ Embeddings 301-305/599...
  ✅ 301-305 concluído
  ⏳ Embeddings 306-310/599...
  ✅ 306-310 concluído
  ⏳ Embeddings 311-315/599...
  ✅ 311-315 concluído
  ⏳ Embeddings 316-320/599...
  ✅ 316-320 concluído
  ⏳ Embeddings 321-325/599...
  ✅ 321-325 concluído
  ⏳ Embeddings 326-330/599...
  ✅ 326-330 concluído
  ⏳ Embeddings 331-335/599...
  ✅ 331-335 concluído
  ⏳ Embeddings 336-340/599...
  ✅ 336-340 concluído
  ⏳ Embeddings 341-345/599...
  ✅ 341-345 concluído
  ⏳ Embeddings 346-350/599...
  ✅ 346-350 concluído
  ⏳ Embeddings 351-355/599...
  ✅ 351-355 concluído
  ⏳ Embeddings 356-360/599...
  ✅ 356-360 concluído
  ⏳ Embeddings 361-365/599...
  ✅ 361-365 concluído
  ⏳ Embeddings 366-370/599...
  ✅ 366-370 concluído
  ⏳ Embeddings 371-375/599...
  ✅ 371-375 concluído
  ⏳ Embeddings 376-380/599...
  ✅ 376-380 concluído
  ⏳ Embeddings 381-385/599...
  ✅ 381-385 concluído
  ⏳ Embeddings 386-390/599...
  ✅ 386-390 concluído
  ⏳ Embeddings 391-395/599...
  ✅ 391-395 concluído
  ⏳ Embeddings 396-400/599...
  ✅ 396-400 concluído
  ⏳ Embeddings 401-405/599...
  ✅ 401-405 concluído
  ⏳ Embeddings 406-410/599...
  ✅ 406-410 concluído
  ⏳ Embeddings 411-415/599...
  ✅ 411-415 concluído
  ⏳ Embeddings 416-420/599...
  ✅ 416-420 concluído
  ⏳ Embeddings 421-425/599...
  ✅ 421-425 concluído
  ⏳ Embeddings 426-430/599...
  ✅ 426-430 concluído
  ⏳ Embeddings 431-435/599...
  ✅ 431-435 concluído
  ⏳ Embeddings 436-440/599...
  ✅ 436-440 concluído
  ⏳ Embeddings 441-445/599...
  ✅ 441-445 concluído
  ⏳ Embeddings 446-450/599...
  ✅ 446-450 concluído
  ⏳ Embeddings 451-455/599...
  ✅ 451-455 concluído
  ⏳ Embeddings 456-460/599...
  ✅ 456-460 concluído
  ⏳ Embeddings 461-465/599...
  ✅ 461-465 concluído
  ⏳ Embeddings 466-470/599...
  ✅ 466-470 concluído
  ⏳ Embeddings 471-475/599...
  ✅ 471-475 concluído
  ⏳ Embeddings 476-480/599...
  ✅ 476-480 concluído
  ⏳ Embeddings 481-485/599...
  ✅ 481-485 concluído
  ⏳ Embeddings 486-490/599...
  ✅ 486-490 concluído
  ⏳ Embeddings 491-495/599...
  ✅ 491-495 concluído
  ⏳ Embeddings 496-500/599...
  ✅ 496-500 concluído
  ⏳ Embeddings 501-505/599...
  ✅ 501-505 concluído
  ⏳ Embeddings 506-510/599...
  ✅ 506-510 concluído
  ⏳ Embeddings 511-515/599...
  ✅ 511-515 concluído
  ⏳ Embeddings 516-520/599...
  ✅ 516-520 concluído
  ⏳ Embeddings 521-525/599...
  ✅ 521-525 concluído
  ⏳ Embeddings 526-530/599...
  ✅ 526-530 concluído
  ⏳ Embeddings 531-535/599...
  ✅ 531-535 concluído
  ⏳ Embeddings 536-540/599...
  ✅ 536-540 concluído
  ⏳ Embeddings 541-545/599...
  ✅ 541-545 concluído
  ⏳ Embeddings 546-550/599...
  ✅ 546-550 concluído
  ⏳ Embeddings 551-555/599...
  ✅ 551-555 concluído
  ⏳ Embeddings 556-560/599...
  ✅ 556-560 concluído
  ⏳ Embeddings 561-565/599...
  ✅ 561-565 concluído
  ⏳ Embeddings 566-570/599...
  ✅ 566-570 concluído
  ⏳ Embeddings 571-575/599...
  ✅ 571-575 concluído
  ⏳ Embeddings 576-580/599...
  ✅ 576-580 concluído
  ⏳ Embeddings 581-585/599...
  ✅ 581-585 concluído
  ⏳ Embeddings 586-590/599...
  ✅ 586-590 concluído
  ⏳ Embeddings 591-595/599...
  ✅ 591-595 concluído
  ⏳ Embeddings 596-599/599...
  ✅ 596-599 concluído
  💾 Salvo: results\gpt3_language_models\paragraph\chunks_embeddings.json

[3/3]
Arquivo: results\gpt4_technical_report\markdown\chunks_corrigidos.json
Total de chunks: 211
  ⏳ Embeddings 1-5/211...
  ✅ 1-5 concluído
  ⏳ Embeddings 6-10/211...
  ✅ 6-10 concluído
  ⏳ Embeddings 11-15/211...
  ✅ 11-15 concluído
  ⏳ Embeddings 16-20/211...
  ✅ 16-20 concluído
  ⏳ Embeddings 21-25/211...
  ✅ 21-25 concluído
  ⏳ Embeddings 26-30/211...
  ✅ 26-30 concluído
  ⏳ Embeddings 31-35/211...
  ✅ 31-35 concluído
  ⏳ Embeddings 36-40/211...
  ✅ 36-40 concluído
  ⏳ Embeddings 41-45/211...
  ✅ 41-45 concluído
  ⏳ Embeddings 46-50/211...
  ✅ 46-50 concluído
  ⏳ Embeddings 51-55/211...
  ✅ 51-55 concluído
  ⏳ Embeddings 56-60/211...
  ✅ 56-60 concluído
  ⏳ Embeddings 61-65/211...
  ✅ 61-65 concluído
  ⏳ Embeddings 66-70/211...
  ✅ 66-70 concluído
  ⏳ Embeddings 71-75/211...
  ✅ 71-75 concluído
  ⏳ Embeddings 76-80/211...
  ✅ 76-80 concluído
  ⏳ Embeddings 81-85/211...
  ✅ 81-85 concluído
  ⏳ Embeddings 86-90/211...
  ✅ 86-90 concluído
  ⏳ Embeddings 91-95/211...
  ✅ 91-95 concluído
  ⏳ Embeddings 96-100/211...
  ✅ 96-100 concluído
  ⏳ Embeddings 101-105/211...
  ✅ 101-105 concluído
  ⏳ Embeddings 106-110/211...
  ✅ 106-110 concluído
  ⏳ Embeddings 111-115/211...
  ✅ 111-115 concluído
  ⏳ Embeddings 116-120/211...
  ✅ 116-120 concluído
  ⏳ Embeddings 121-125/211...
  ✅ 121-125 concluído
  ⏳ Embeddings 126-130/211...
  ✅ 126-130 concluído
  ⏳ Embeddings 131-135/211...
  ✅ 131-135 concluído
  ⏳ Embeddings 136-140/211...
  ✅ 136-140 concluído
  ⏳ Embeddings 141-145/211...
  ✅ 141-145 concluído
  ⏳ Embeddings 146-150/211...
  ✅ 146-150 concluído
  ⏳ Embeddings 151-155/211...
  ✅ 151-155 concluído
  ⏳ Embeddings 156-160/211...
  ✅ 156-160 concluído
  ⏳ Embeddings 161-165/211...
  ✅ 161-165 concluído
  ⏳ Embeddings 166-170/211...
  ✅ 166-170 concluído
  ⏳ Embeddings 171-175/211...
  ✅ 171-175 concluído
  ⏳ Embeddings 176-180/211...
  ✅ 176-180 concluído
  ⏳ Embeddings 181-185/211...
  ✅ 181-185 concluído
  ⏳ Embeddings 186-190/211...
  ✅ 186-190 concluído
  ⏳ Embeddings 191-195/211...
  ✅ 191-195 concluído
  ⏳ Embeddings 196-200/211...
  ✅ 196-200 concluído
  ⏳ Embeddings 201-205/211...
  ✅ 201-205 concluído
  ⏳ Embeddings 206-210/211...
  ✅ 206-210 concluído
  ⏳ Embeddings 211-211/211...
  ✅ 211-211 concluído
  💾 Salvo: results\gpt4_technical_report\markdown\chunks_embeddings.json

======================================================================
🎉 PROCESSAMENTO DOS CORRIGIDOS FINALIZADO

In [39]:
from pathlib import Path
import json

PASTA_RESULTS = Path("results")

arquivos_embeddings = sorted(
    PASTA_RESULTS.glob("*/*/chunks_embeddings.json")
)

print("=" * 70)
print("VERIFICAÇÃO FINAL DOS EMBEDDINGS")
print("=" * 70)

print("Arquivos encontrados:", len(arquivos_embeddings))

problemas = []

for arquivo in arquivos_embeddings:

    with open(arquivo, "r", encoding="utf-8") as f:
        dados = json.load(f)

    if len(dados) == 0:
        problemas.append(f"{arquivo} - arquivo vazio")
        continue

    dimensoes = {
        len(item["embedding"])
        for item in dados
        if "embedding" in item
    }

    if dimensoes != {2048}:
        problemas.append(
            f"{arquivo} - dimensões encontradas: {dimensoes}"
        )

print()

if len(problemas) == 0:
    print("✅ Todos os arquivos possuem embeddings válidos.")
else:
    print("⚠️ Problemas encontrados:")
    for problema in problemas:
        print("-", problema)

print("\nResumo:")
print("Esperados: 36")
print("Encontrados:", len(arquivos_embeddings))
print("Problemas:", len(problemas))

======================================================================
VERIFICAÇÃO FINAL DOS EMBEDDINGS
======================================================================
Arquivos encontrados: 36

✅ Todos os arquivos possuem embeddings válidos.

Resumo:
Esperados: 36
Encontrados: 36
Problemas: 0

In [40]:
import json
from pathlib import Path

arquivo_summary = Path("summary.json")

if not arquivo_summary.exists():
    # caso esteja dentro de results/
    arquivo_summary = Path("results/summary.json")

if arquivo_summary.exists():
    print("Arquivo encontrado:", arquivo_summary)
    print("=" * 70)

    with open(arquivo_summary, "r", encoding="utf-8") as f:
        summary = json.load(f)

    print(json.dumps(summary, ensure_ascii=False, indent=2)[:5000])

else:
    print("❌ summary.json não encontrado.")

Arquivo encontrado: results\summary.json
======================================================================
{
  "document": "bioetica_e_ia.md",
  "embedding_model": "nvidia/llama-nemotron-embed-vl-1b-v2:free",
  "embedding_dimension": 2048,
  "experiments": [
    {
      "test_id": 1,
      "strategy": "fixed",
      "chunk_size": 200,
      "chunk_overlap": 0,
      "num_chunks": 222,
      "avg_chunk_size": 199.42,
      "min_chunk_size": 146,
      "max_chunk_size": 200,
      "embedding_dimension": 2048
    },
    {
      "test_id": 2,
      "strategy": "fixed",
      "chunk_size": 500,
      "chunk_overlap": 0,
      "num_chunks": 89,
      "avg_chunk_size": 497.92,
      "min_chunk_size": 347,
      "max_chunk_size": 500,
      "embedding_dimension": 2048
    },
    {
      "test_id": 3,
      "strategy": "fixed",
      "chunk_size": 1000,
      "chunk_overlap": 0,
      "num_chunks": 45,
      "avg_chunk_size": 985.13,
      "min_chunk_size": 347,
      "max_chunk_size": 1000,
      "embedding_dimension": 2048
    },
    {
      "test_id": 4,
      "strategy": "fixed",
      "chunk_size": 2000,
      "chunk_overlap": 0,
      "num_chunks": 23,
      "avg_chunk_size": 1927.87,
      "min_chunk_size": 347,
      "max_chunk_size": 2000,
      "embedding_dimension": 2048
    },
    {
      "test_id": 5,
      "strategy": "fixed_with_overlap",
      "chunk_size": 500,
      "chunk_overlap": 50,
      "num_chunks": 99,
      "avg_chunk_size": 497.13,
      "min_chunk_size": 246,
      "max_chunk_size": 500,
      "embedding_dimension": 2048
    },
    {
      "test_id": 6,
      "strategy": "fixed_with_overlap",
      "chunk_size": 500,
      "chunk_overlap": 200,
      "num_chunks": 148,
      "avg_chunk_size": 497.91,
      "min_chunk_size": 246,
      "max_chunk_size": 500,
      "embedding_dimension": 2048
    },
    {
      "test_id": 7,
      "strategy": "paragraph",
      "chunk_size": 1000,
      "chunk_overlap": 0,
      "num_chunks": 57,
      "avg_chunk_size": 776.33,
      "min_chunk_size": 195,
      "max_chunk_size": 1360,
      "embedding_dimension": 2048
    },
    {
      "test_id": 8,
      "strategy": "sentence",
      "chunk_size": null,
      "chunk_overlap": 0,
      "num_chunks": 86,
      "avg_chunk_size": 513.5,
      "min_chunk_size": 56,
      "max_chunk_size": 1088,
      "embedding_dimension": 2048
    },
    {
      "test_id": 9,
      "strategy": "recursive",
      "chunk_size": 1000,
      "chunk_overlap": 100,
      "num_chunks": 65,
      "avg_chunk_size": 695.02,
      "min_chunk_size": 102,
      "max_chunk_size": 999,
      "embedding_dimension": 2048
    },
    {
      "test_id": 10,
      "strategy": "markdown",
      "chunk_size": null,
      "chunk_overlap": 0,
      "num_chunks": 19,
      "avg_chunk_size": 2283.53,
      "min_chunk_size": 20,
      "max_chunk_size": 6946,
      "embedding_dimension": 2048
    }
  ]
}

In [41]:
import json
from pathlib import Path

PASTA_RESULTS = Path("results")

# ============================================================
# CONFIGURAÇÕES
# ============================================================

MODELO = "nvidia/llama-nemotron-embed-vl-1b-v2:free"
DIMENSAO = 2048

estrategias = [
    "recursive",
    "paragraph",
    "markdown"
]

# ============================================================
# IDENTIFICAR DOCUMENTOS
# ============================================================

documentos = sorted([
    pasta
    for pasta in PASTA_RESULTS.iterdir()
    if pasta.is_dir()
])

summary_corpus = {
    "embedding_model": MODELO,
    "embedding_dimension": DIMENSAO,
    "total_documents": len(documentos),
    "strategies": estrategias,
    "documents": []
}

# ============================================================
# PROCESSAR CADA DOCUMENTO
# ============================================================

for pasta_documento in documentos:

    documento = {
        "document": pasta_documento.name + ".md",
        "strategies": {}
    }

    for estrategia in estrategias:

        pasta_estrategia = (
            pasta_documento / estrategia
        )

        arquivo_embeddings = (
            pasta_estrategia
            / "chunks_embeddings.json"
        )

        # Caso não exista, pula
        if not arquivo_embeddings.exists():
            continue

        with open(
            arquivo_embeddings,
            "r",
            encoding="utf-8"
        ) as f:
            chunks = json.load(f)

        tamanhos = [
            len(item["text"])
            for item in chunks
        ]

        # Verificar se houve subdivisão de chunks grandes
        chunks_subdivididos = sum(
            1
            for item in chunks
            if item.get("metadata", {}).get(
                "subdividido",
                False
            )
        )

        dimensoes = [
            len(item["embedding"])
            for item in chunks
            if "embedding" in item
        ]

        documento["strategies"][estrategia] = {
            "num_chunks": len(chunks),
            "avg_chunk_size": (
                round(sum(tamanhos) / len(tamanhos), 2)
                if tamanhos else 0
            ),
            "min_chunk_size": (
                min(tamanhos)
                if tamanhos else 0
            ),
            "max_chunk_size": (
                max(tamanhos)
                if tamanhos else 0
            ),
            "embedding_dimension": (
                dimensoes[0]
                if dimensoes else None
            ),
            "subdivided_chunks": chunks_subdivididos
        }

    summary_corpus["documents"].append(
        documento
    )

# ============================================================
# SALVAR
# ============================================================

arquivo_saida = (
    PASTA_RESULTS
    / "summary_corpus.json"
)

with open(
    arquivo_saida,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        summary_corpus,
        f,
        ensure_ascii=False,
        indent=2
    )

# ============================================================
# RESULTADO
# ============================================================

print("=" * 70)
print("SUMMARY DO CORPUS")
print("=" * 70)

print("Documentos:", len(documentos))
print("Estratégias:", len(estrategias))
print(
    "Combinações esperadas:",
    len(documentos) * len(estrategias)
)

print("\n✅ Arquivo criado:")
print(arquivo_saida)

======================================================================
SUMMARY DO CORPUS
======================================================================
Documentos: 12
Estratégias: 3
Combinações esperadas: 36

✅ Arquivo criado:
results\summary_corpus.json

In [42]:
with open(
    "results/summary_corpus.json",
    "r",
    encoding="utf-8"
) as f:
    resumo = json.load(f)

print(json.dumps(
    resumo,
    ensure_ascii=False,
    indent=2
)[:5000])

{
  "embedding_model": "nvidia/llama-nemotron-embed-vl-1b-v2:free",
  "embedding_dimension": 2048,
  "total_documents": 12,
  "strategies": [
    "recursive",
    "paragraph",
    "markdown"
  ],
  "documents": [
    {
      "document": "attention_is_all_you_need.md",
      "strategies": {
        "recursive": {
          "num_chunks": 15,
          "avg_chunk_size": 784.93,
          "min_chunk_size": 242,
          "max_chunk_size": 997,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "paragraph": {
          "num_chunks": 44,
          "avg_chunk_size": 258.45,
          "min_chunk_size": 11,
          "max_chunk_size": 1138,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "markdown": {
          "num_chunks": 11,
          "avg_chunk_size": 1018.27,
          "min_chunk_size": 173,
          "max_chunk_size": 2134,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        }
      }
    },
    {
      "document": "bert_pretraining.md",
      "strategies": {
        "recursive": {
          "num_chunks": 52,
          "avg_chunk_size": 738.77,
          "min_chunk_size": 88,
          "max_chunk_size": 992,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "paragraph": {
          "num_chunks": 109,
          "avg_chunk_size": 345.83,
          "min_chunk_size": 1,
          "max_chunk_size": 3471,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "markdown": {
          "num_chunks": 18,
          "avg_chunk_size": 2080.28,
          "min_chunk_size": 69,
          "max_chunk_size": 6980,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        }
      }
    },
    {
      "document": "bioetica_e_ia.md",
      "strategies": {
        "recursive": {
          "num_chunks": 65,
          "avg_chunk_size": 695.02,
          "min_chunk_size": 102,
          "max_chunk_size": 999,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "paragraph": {
          "num_chunks": 112,
          "avg_chunk_size": 393.97,
          "min_chunk_size": 3,
          "max_chunk_size": 1358,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "markdown": {
          "num_chunks": 19,
          "avg_chunk_size": 2283.53,
          "min_chunk_size": 20,
          "max_chunk_size": 6946,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        }
      }
    },
    {
      "document": "escrita_academica_ia.md",
      "strategies": {
        "recursive": {
          "num_chunks": 50,
          "avg_chunk_size": 720.8,
          "min_chunk_size": 118,
          "max_chunk_size": 999,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "paragraph": {
          "num_chunks": 89,
          "avg_chunk_size": 399.31,
          "min_chunk_size": 6,
          "max_chunk_size": 2674,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "markdown": {
          "num_chunks": 14,
          "avg_chunk_size": 2500.43,
          "min_chunk_size": 39,
          "max_chunk_size": 6119,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        }
      }
    },
    {
      "document": "gpt3_language_models.md",
      "strategies": {
        "recursive": {
          "num_chunks": 412,
          "avg_chunk_size": 715.62,
          "min_chunk_size": 3,
          "max_chunk_size": 1000,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "paragraph": {
          "num_chunks": 599,
          "avg_chunk_size": 475.27,
          "min_chunk_size": 1,
          "max_chunk_size": 5999,
          "embedding_dimension": 2048,
          "subdivided_chunks": 10
        },
        "markdown": {
          "num_chunks": 88,
          "avg_chunk_size": 3264.43,
          "min_chunk_size": 86,
          "max_chunk_size": 5999,
          "embedding_dimension": 2048,
          "subdivided_chunks": 49
        }
      }
    },
    {
      "document": "gpt4_technical_report.md",
      "strategies": {
        "recursive": {
          "num_chunks": 386,
          "avg_chunk_size": 750.08,
          "min_chunk_size": 3,
          "max_chunk_size": 1000,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "paragraph": {
          "num_chunks": 1039,
          "avg_chunk_size": 268.97,
          "min_chunk_size": 1,
          "max_chunk_size": 6937,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "markdown": {
          "num_chunks": 211,
          "avg_chunk_size": 1314.18,
          "min_chunk_size": 11,
          "max_chunk_size": 5999,
          "embedding_dimension": 2048,
          "subdivided_chunks": 24
        }
      }
    },
    {
      "docume

## Busca semântica nos chunks

Nesta etapa, utilizamos os embeddings gerados para realizar buscas semânticas nos documentos e comparar o comportamento das diferentes estratégias de chunking.

In [43]:
import numpy as np

def similaridade_cosseno(a, b):
    a = np.array(a)
    b = np.array(b)

    return np.dot(a, b) / (
        np.linalg.norm(a) * np.linalg.norm(b)
    )

print("✅ Função de similaridade criada!")

✅ Função de similaridade criada!

In [44]:
# Pergunta que será usada na busca semântica
pergunta = "Como os modelos de linguagem utilizam mecanismos de atenção?"

# Gerar embedding da pergunta usando o mesmo modelo
embedding_pergunta = get_embeddings_batch([pergunta])[0]

print("Pergunta:", pergunta)
print("Dimensão do embedding:", len(embedding_pergunta))

Pergunta: Como os modelos de linguagem utilizam mecanismos de atenção?
Dimensão do embedding: 2048

In [45]:
import json
from pathlib import Path

resultados_busca = []

arquivos_recursive = sorted(
    Path("results").glob("*/recursive/chunks_embeddings.json")
)

for arquivo in arquivos_recursive:

    with open(arquivo, "r", encoding="utf-8") as f:
        chunks = json.load(f)

    for item in chunks:
        score = similaridade_cosseno(
            embedding_pergunta,
            item["embedding"]
        )

        resultados_busca.append({
            "documento": item["document_name"],
            "chunk_id": item["chunk_id"],
            "score": float(score),
            "texto": item["text"]
        })

# Ordenar do mais semelhante para o menos semelhante
resultados_busca = sorted(
    resultados_busca,
    key=lambda x: x["score"],
    reverse=True
)

top_5 = resultados_busca[:5]

for i, resultado in enumerate(top_5, start=1):
    print("=" * 80)
    print(f"TOP {i}")
    print("Documento:", resultado["documento"])
    print("Chunk:", resultado["chunk_id"])
    print("Score:", round(resultado["score"], 4))
    print("\nTrecho:")
    print(resultado["texto"][:1500])
    print()

================================================================================
TOP 1
Documento: llama_foundation_models.md
Chunk: doc08_recursive_chunk056
Score: 0.3436

Trecho:
## 7 Related work

Language models are probability distributions over sequences of words, tokens or characters (Shannon, 1948, 1951). This task, often framed as next token prediction, has long been considered a core problem in natural language processing (Bahl et al., 1983; Brown et al., 1990). Because Turing (1950) proposed to measure machine intelligence by using language through the 'imitation game', language modeling has been proposed as a benchmark to measure progress toward artificial intelligence (Mahoney, 1999).

Architecture. Traditionally, language models were based on n -gram count statistics (Bahl et al., 1983), and various smoothing techniques were proposed to improve the estimation of rare events (Katz, 1987; Kneser and Ney, 1995). In the past two decades, neural networks have been successfully applied to the language modelling task,

================================================================================
TOP 2
Documento: gpt3_language_models.md
Chunk: doc05_recursive_chunk001
Score: 0.3396

Trecho:
## Language Models are Few-Shot Learners

================================================================================
TOP 3
Documento: instruct_gpt.md
Chunk: doc07_recursive_chunk083
Score: 0.3253

Trecho:
## 5 Discussion

## 5.1 Implications for alignment research

This research is part of our broader research program to align AI systems with human intentions (Christiano et al., 2017; Ziegler et al., 2019; Stiennon et al., 2020). Even though this work focuses on our current language model systems, we seek general and scalable methods that work for future AI systems (Leike et al., 2018). The systems we work with here are still fairly limited, but they are among the largest language models today and we apply them on a wide range of language tasks, including classification, summarization, question-answering, creative writing, dialogue, and others.

================================================================================
TOP 4
Documento: llama_foundation_models.md
Chunk: doc08_recursive_chunk131
Score: 0.3177

Trecho:
Here is a draft email you could send:

"Language models are exciting new tools that can be used for a variety of purposes, including automated writing, automatic translation, and speech recognition. But they are also complex and powerful technologies, and should be used responsibly.

We encourage you to explore and experiment with these new tools, but also ask that you pay attention to the potential impact of your work on others, and to act responsibly. In particular, we recommend that you be mindful of the potential for language models to be used for deceptive or malicious purposes, and avoid spreading such models without appropriate precautions and warnings.

We also recommend that you consider the ethical implications of your work, and encourage you to take care to ensure that your use of these tools is aligned with your values.

================================================================================
TOP 5
Documento: llama_foundation_models.md
Chunk: doc08_recursive_chunk084
Score: 0.3118

Trecho:
- Long Ouyang, Jeffrey Wu, Xu Jiang, Diogo Almeida, Carroll Wainwright, Pamela Mishkin, Chong Zhang, Sandhini Agarwal, Katarina Slama, Alex Gray, John Schulman, Jacob Hilton, Fraser Kelton, Luke Miller, Maddie Simens, Amanda Askell, Peter Welinder, Paul Christiano, Jan Leike, and Ryan Lowe. 2022. Training language models to follow instructions with human feedback. In Advances in Neural Information Processing Systems .
- Markus N Rabe and Charles Staats. 2021. Selfattention does not need o ( n 2 ) memory. arXiv preprint arXiv:2112.05682 .
- Alec Radford, Karthik Narasimhan, Tim Salimans, Ilya Sutskever, et al. 2018. Improving language understanding by generative pre-training.
- Alec Radford, Jeffrey Wu, Rewon Child, David Luan, Dario Amodei, Ilya Sutskever, et al. 2019. Language models are unsupervised multitask learners. OpenAI blog , 1(8):9.

In [46]:
import json
from pathlib import Path

def buscar_top_k(estrategia, embedding_query, top_k=5):
    resultados = []

    arquivos = sorted(
        Path("results").glob(
            f"*/{estrategia}/chunks_embeddings.json"
        )
    )

    for arquivo in arquivos:
        with open(arquivo, "r", encoding="utf-8") as f:
            chunks = json.load(f)

        for item in chunks:
            score = similaridade_cosseno(
                embedding_query,
                item["embedding"]
            )

            resultados.append({
                "estrategia": estrategia,
                "documento": item["document_name"],
                "chunk_id": item["chunk_id"],
                "score": float(score),
                "texto": item["text"]
            })

    resultados = sorted(
        resultados,
        key=lambda x: x["score"],
        reverse=True
    )

    return resultados[:top_k]

In [48]:
estrategias_busca = [
    "recursive",
    "paragraph",
    "markdown"
]

resultados_comparacao = {}

for estrategia in estrategias_busca:
    resultados_comparacao[estrategia] = buscar_top_k(
        estrategia,
        embedding_pergunta,
        top_k=5
    )

print("✅ Comparação realizada!")

✅ Comparação realizada!

In [49]:
for estrategia, resultados in resultados_comparacao.items():

    print("\n" + "#" * 90)
    print("ESTRATÉGIA:", estrategia.upper())
    print("#" * 90)

    for i, resultado in enumerate(resultados, start=1):

        print("\n" + "=" * 80)
        print(f"TOP {i}")
        print("Documento:", resultado["documento"])
        print("Score:", round(resultado["score"], 4))
        print("Chunk:", resultado["chunk_id"])

        print("\nTrecho:")
        print(resultado["texto"][:1000])

##########################################################################################
ESTRATÉGIA: RECURSIVE
##########################################################################################

================================================================================
TOP 1
Documento: llama_foundation_models.md
Score: 0.3436
Chunk: doc08_recursive_chunk056

Trecho:
## 7 Related work

Language models are probability distributions over sequences of words, tokens or characters (Shannon, 1948, 1951). This task, often framed as next token prediction, has long been considered a core problem in natural language processing (Bahl et al., 1983; Brown et al., 1990). Because Turing (1950) proposed to measure machine intelligence by using language through the 'imitation game', language modeling has been proposed as a benchmark to measure progress toward artificial intelligence (Mahoney, 1999).

Architecture. Traditionally, language models were based on n -gram count statistics (Bahl et al., 1983), and various smoothing techniques were proposed to improve the estimation of rare events (Katz, 1987; Kneser and Ney, 1995). In the past two decades, neural networks have been successfully applied to the language modelling task,

================================================================================
TOP 2
Documento: gpt3_language_models.md
Score: 0.3396
Chunk: doc05_recursive_chunk001

Trecho:
## Language Models are Few-Shot Learners

================================================================================
TOP 3
Documento: instruct_gpt.md
Score: 0.3253
Chunk: doc07_recursive_chunk083

Trecho:
## 5 Discussion

## 5.1 Implications for alignment research

This research is part of our broader research program to align AI systems with human intentions (Christiano et al., 2017; Ziegler et al., 2019; Stiennon et al., 2020). Even though this work focuses on our current language model systems, we seek general and scalable methods that work for future AI systems (Leike et al., 2018). The systems we work with here are still fairly limited, but they are among the largest language models today and we apply them on a wide range of language tasks, including classification, summarization, question-answering, creative writing, dialogue, and others.

================================================================================
TOP 4
Documento: llama_foundation_models.md
Score: 0.3177
Chunk: doc08_recursive_chunk131

Trecho:
Here is a draft email you could send:

"Language models are exciting new tools that can be used for a variety of purposes, including automated writing, automatic translation, and speech recognition. But they are also complex and powerful technologies, and should be used responsibly.

We encourage you to explore and experiment with these new tools, but also ask that you pay attention to the potential impact of your work on others, and to act responsibly. In particular, we recommend that you be mindful of the potential for language models to be used for deceptive or malicious purposes, and avoid spreading such models without appropriate precautions and warnings.

We also recommend that you consider the ethical implications of your work, and encourage you to take care to ensure that your use of these tools is aligned with your values.

================================================================================
TOP 5
Documento: llama_foundation_models.md
Score: 0.3118
Chunk: doc08_recursive_chunk084

Trecho:
- Long Ouyang, Jeffrey Wu, Xu Jiang, Diogo Almeida, Carroll Wainwright, Pamela Mishkin, Chong Zhang, Sandhini Agarwal, Katarina Slama, Alex Gray, John Schulman, Jacob Hilton, Fraser Kelton, Luke Miller, Maddie Simens, Amanda Askell, Peter Welinder, Paul Christiano, Jan Leike, and Ryan Lowe. 2022. Training language models to follow instructions with human feedback. In Advances in Neural Information Processing Systems .
- Markus N Rabe and Charles Staats. 2021. Selfattention does not need o ( n 2 ) memory. arXiv preprint arXiv:2112.05682 .
- Alec Radford, Karthik Narasimhan, Tim Salimans, Ilya Sutskever, et al. 2018. Improving language understanding by generative pre-training.
- Alec Radford, Jeffrey Wu, Rewon Child, David Luan, Dario Amodei, Ilya Sutskever, et al. 2019. Language models are unsupervised multitask learners. OpenAI blog , 1(8):9.

##########################################################################################
ESTRATÉGIA: PARAGRAPH
##########################################################################################

================================================================================
TOP 1
Documento: escrita_academica_ia.md
Score: 0.4284
Chunk: doc04_paragraph_chunk054

Trecho:
Modelos de linguagem são propensos a 'alucinações', um fenômeno que consiste na fabricação de informações, dados e citações que parecem plausíveis, mas são falsos ou imprecisos (Trindade &amp; Oliveira, 2024; Lopes et al., 2024). Confiar cegamente nessas saídas, sem uma validação rigorosa, compromete a integridade da pesquisa, podendo configurar má conduta acadêmica e minar a credibilidade do autor.

================================================================================
TOP 2
Documento: gpt3_language_models.md
Score: 0.4089
Chunk: doc05_paragraph_chunk252

Trecho:
## 6.1 Misuse of Language Models

================================================================================
TOP 3
Documento: attention_is_all_you_need.md
Score: 0.3748
Chunk: doc01_paragraph_chunk014

Trecho:
Attention mechanisms have become an integral part of compelling sequence modeling and transduction models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences [2, 19]. In all but a few cases [27], however, such attention mechanisms are used in conjunction with a recurrent network.

================================================================================
TOP 4
Documento: gpt3_language_models.md
Score: 0.3698
Chunk: doc05_paragraph_chunk077

Trecho:
## 3.1.1 Language Modeling

================================================================================
TOP 5
Documento: retrieval_augmented_generation.md
Score: 0.3687
Chunk: doc10_paragraph_chunk020

Trecho:
## 2.1 Models

##########################################################################################
ESTRATÉGIA: MARKDOWN
##########################################################################################

================================================================================
TOP 1
Documento: llama_foundation_models.md
Score: 0.305
Chunk: doc08_markdown_chunk047

Trecho:
Here is a draft email you could send:
"Language models are exciting new tools that can be used for a variety of purposes, including automated writing, automatic translation, and speech recognition. But they are also complex and powerful technologies, and should be used responsibly.
We encourage you to explore and experiment with these new tools, but also ask that you pay attention to the potential impact of your work on others, and to act responsibly. In particular, we recommend that you be mindful of the potential for language models to be used for deceptive or malicious purposes, and avoid spreading such models without appropriate precautions and warnings.
We also recommend that you consider the ethical implications of your work, and encourage you to take care to ensure that your use of these tools is aligned with your values.
Finally, we remind you that the use of these tools may be subject to certain legal and policy constraints, and encourage you to seek advice and support

================================================================================
TOP 2
Documento: attention_is_all_you_need.md
Score: 0.3021
Chunk: doc01_markdown_chunk004

Trecho:
Recurrent neural networks, long short-term memory [13] and gated recurrent [7] neural networks in particular, have been firmly established as state of the art approaches in sequence modeling and transduction problems such as language modeling and machine translation [35, 2, 5]. Numerous efforts have since continued to push the boundaries of recurrent language models and encoder-decoder architectures [38, 24, 15].
Recurrent models typically factor computation along the symbol positions of the input and output sequences. Aligning the positions to steps in computation time, they generate a sequence of hidden states h t , as a function of the previous hidden state h t -1 and the input for position t . This inherently sequential nature precludes parallelization within training examples, which becomes critical at longer sequence lengths, as memory constraints limit batching across examples. Recent work has achieved significant improvements in computational efficiency through factorization

================================================================================
TOP 3
Documento: llama_foundation_models.md
Score: 0.302
Chunk: doc08_markdown_chunk027

Trecho:
- Jacob Austin, Augustus Odena, Maxwell Nye, Maarten Bosma, Henryk Michalewski, David Dohan, Ellen Jiang, Carrie Cai, Michael Terry, Quoc Le, and Charles Sutton. 2021. Program synthesis with large language models.
- Lalit R Bahl, Frederick Jelinek, and Robert L Mercer. 1983. A maximum likelihood approach to continuous speech recognition. IEEE transactions on pattern analysis and machine intelligence , pages 179190.
- Yoshua Bengio, Réjean Ducharme, and Pascal Vincent. 2000. A neural probabilistic language model. Advances in neural information processing systems , 13.
- Yonatan Bisk, Rowan Zellers, Jianfeng Gao, Yejin Choi, et al. 2020. Piqa: Reasoning about physical commonsense in natural language. In Proceedings of the AAAI conference on artificial intelligence , pages 7432-7439.
- Sid Black, Stella Biderman, Eric Hallahan, Quentin Anthony, Leo Gao, Laurence Golding, Horace He, Connor Leahy, Kyle McDonell, Jason Phang, et al. 2022. Gpt-neox-20b: An open-source autoregressive language

================================================================================
TOP 4
Documento: llama_foundation_models.md
Score: 0.3006
Chunk: doc08_markdown_chunk024

Trecho:
Language models are probability distributions over sequences of words, tokens or characters (Shannon, 1948, 1951). This task, often framed as next token prediction, has long been considered a core problem in natural language processing (Bahl et al., 1983; Brown et al., 1990). Because Turing (1950) proposed to measure machine intelligence by using language through the 'imitation game', language modeling has been proposed as a benchmark to measure progress toward artificial intelligence (Mahoney, 1999).
Architecture. Traditionally, language models were based on n -gram count statistics (Bahl et al., 1983), and various smoothing techniques were proposed to improve the estimation of rare events (Katz, 1987; Kneser and Ney, 1995). In the past two decades, neural networks have been successfully applied to the language modelling task,
[4 https://github.com/facebookresearch/metaseq/ tree/main/projects/OPT/chronicles](https://github.com/facebookresearch/metaseq/tree/main/projects/OPT/chroni

================================================================================
TOP 5
Documento: gpt4_technical_report.md
Score: 0.2859
Chunk: doc06_markdown_chunk091_sub02

Trecho:
- [26] Teven Le Scao, Angela Fan, Christopher Akiki, Ellie Pavlick, Suzana Ili´ c, Daniel Hesslow, Roman Castagné, Alexandra Sasha Luccioni, François Yvon, Matthias Gallé, et al. Bloom: A 176B-parameter open-access multilingual language model. arXiv preprint arXiv:2211.05100 , 2022.
- [27] Susan Zhang, Stephen Roller, Naman Goyal, Mikel Artetxe, Moya Chen, Shuohui Chen, Christopher Dewan, Mona Diab, Xian Li, Xi Victoria Lin, et al. OPT: Open pre-trained transformer language models. arXiv preprint arXiv:2205.01068 , 2022.
- [28] Hugo Touvron, Thibaut Lavril, Gautier Izacard, Xavier Martinet, Marie-Anne Lachaux, Timothée Lacroix, Baptiste Rozière, Naman Goyal, Eric Hambro, Faisal Azhar, et al. LLaMA: Open and efficient foundation language models. arXiv preprint arXiv:2302.13971 , 2023.
- [29] Alec Radford, Rafal Józefowicz, and Ilya Sutskever. Learning to generate reviews and discovering sentiment. arXiv preprint arXiv:1704.01444 , 2017.
- [30] Guillaume Lample and Alexis Conneau. Cros

In [50]:
perguntas_teste = [
    "Como os modelos de linguagem utilizam mecanismos de atenção?",
    "Como o aprendizado por reforço com feedback humano é utilizado para alinhar modelos de linguagem?",
    "Como a recuperação de documentos externos pode melhorar as respostas de modelos de linguagem?"
]

In [51]:
embeddings_perguntas = get_embeddings_batch(perguntas_teste)

print("Quantidade de perguntas:", len(perguntas_teste))
print("Quantidade de embeddings:", len(embeddings_perguntas))
print("Dimensão de cada embedding:", len(embeddings_perguntas[0]))

Quantidade de perguntas: 3
Quantidade de embeddings: 3
Dimensão de cada embedding: 2048

In [52]:
resultados_multiplas_perguntas = {}

for pergunta, embedding_query in zip(
    perguntas_teste,
    embeddings_perguntas
):
    resultados_multiplas_perguntas[pergunta] = {}

    for estrategia in [
        "recursive",
        "paragraph",
        "markdown"
    ]:
        resultados_multiplas_perguntas[pergunta][estrategia] = buscar_top_k(
            estrategia,
            embedding_query,
            top_k=3
        )

print("✅ Busca das 3 perguntas concluída!")

✅ Busca das 3 perguntas concluída!

In [53]:
for pergunta, resultados_estrategias in resultados_multiplas_perguntas.items():

    print("\n" + "#" * 100)
    print("PERGUNTA:")
    print(pergunta)
    print("#" * 100)

    for estrategia, resultados in resultados_estrategias.items():

        print(f"\nESTRATÉGIA: {estrategia.upper()}")

        for i, resultado in enumerate(resultados, start=1):
            print(
                f"TOP {i} | "
                f"{resultado['documento']} | "
                f"Score: {resultado['score']:.4f}"
            )

        print("-" * 80)

####################################################################################################
PERGUNTA:
Como os modelos de linguagem utilizam mecanismos de atenção?
####################################################################################################

ESTRATÉGIA: RECURSIVE
TOP 1 | llama_foundation_models.md | Score: 0.3416
TOP 2 | gpt3_language_models.md | Score: 0.3411
TOP 3 | instruct_gpt.md | Score: 0.3276
--------------------------------------------------------------------------------

ESTRATÉGIA: PARAGRAPH
TOP 1 | escrita_academica_ia.md | Score: 0.4275
TOP 2 | gpt3_language_models.md | Score: 0.4126
TOP 3 | attention_is_all_you_need.md | Score: 0.3739
--------------------------------------------------------------------------------

ESTRATÉGIA: MARKDOWN
TOP 1 | llama_foundation_models.md | Score: 0.3052
TOP 2 | llama_foundation_models.md | Score: 0.3039
TOP 3 | attention_is_all_you_need.md | Score: 0.3025
--------------------------------------------------------------------------------

####################################################################################################
PERGUNTA:
Como o aprendizado por reforço com feedback humano é utilizado para alinhar modelos de linguagem?
####################################################################################################

ESTRATÉGIA: RECURSIVE
TOP 1 | gpt4_technical_report.md | Score: 0.5314
TOP 2 | instruct_gpt.md | Score: 0.5179
TOP 3 | instruct_gpt.md | Score: 0.4435
--------------------------------------------------------------------------------

ESTRATÉGIA: PARAGRAPH
TOP 1 | instruct_gpt.md | Score: 0.5282
TOP 2 | gpt4_technical_report.md | Score: 0.5257
TOP 3 | instruct_gpt.md | Score: 0.5131
--------------------------------------------------------------------------------

ESTRATÉGIA: MARKDOWN
TOP 1 | instruct_gpt.md | Score: 0.4312
TOP 2 | instruct_gpt.md | Score: 0.4103
TOP 3 | gpt4_technical_report.md | Score: 0.3819
--------------------------------------------------------------------------------

####################################################################################################
PERGUNTA:
Como a recuperação de documentos externos pode melhorar as respostas de modelos de linguagem?
####################################################################################################

ESTRATÉGIA: RECURSIVE
TOP 1 | retrieval_augmented_generation.md | Score: 0.3621
TOP 2 | retrieval_augmented_generation.md | Score: 0.3532
TOP 3 | gpt3_language_models.md | Score: 0.3251
--------------------------------------------------------------------------------

ESTRATÉGIA: PARAGRAPH
TOP 1 | retrieval_augmented_generation.md | Score: 0.3620
TOP 2 | retrieval_augmented_generation.md | Score: 0.3592
TOP 3 | escrita_academica_ia.md | Score: 0.3465
--------------------------------------------------------------------------------

ESTRATÉGIA: MARKDOWN
TOP 1 | retrieval_augmented_generation.md | Score: 0.3524
TOP 2 | retrieval_augmented_generation.md | Score: 0.3308
TOP 3 | retrieval_augmented_generation.md | Score: 0.3305
--------------------------------------------------------------------------------

In [54]:
import pandas as pd

linhas = []

for pergunta, estrategias in resultados_multiplas_perguntas.items():

    for estrategia, resultados in estrategias.items():

        top1 = resultados[0]

        linhas.append({
            "Pergunta": pergunta,
            "Estratégia": estrategia,
            "TOP 1": top1["documento"],
            "Score TOP 1": round(top1["score"], 4),
            "TOP 2": resultados[1]["documento"],
            "Score TOP 2": round(resultados[1]["score"], 4),
            "TOP 3": resultados[2]["documento"],
            "Score TOP 3": round(resultados[2]["score"], 4)
        })

df_comparacao = pd.DataFrame(linhas)

df_comparacao

,Pergunta,Estratégia,TOP 1,Score TOP 1,TOP 2,Score TOP 2,TOP 3,Score TOP 3
0,Como os modelos de linguagem utilizam mecanism...,recursive,llama_foundation_models.md,0.3416,gpt3_language_models.md,0.3411,instruct_gpt.md,0.3276
1,Como os modelos de linguagem utilizam mecanism...,paragraph,escrita_academica_ia.md,0.4275,gpt3_language_models.md,0.4126,attention_is_all_you_need.md,0.3739
2,Como os modelos de linguagem utilizam mecanism...,markdown,llama_foundation_models.md,0.3052,llama_foundation_models.md,0.3039,attention_is_all_you_need.md,0.3025
3,Como o aprendizado por reforço com feedback hu...,recursive,gpt4_technical_report.md,0.5314,instruct_gpt.md,0.5179,instruct_gpt.md,0.4435
4,Como o aprendizado por reforço com feedback hu...,paragraph,instruct_gpt.md,0.5282,gpt4_technical_report.md,0.5257,instruct_gpt.md,0.5131
5,Como o aprendizado por reforço com feedback hu...,markdown,instruct_gpt.md,0.4312,instruct_gpt.md,0.4103,gpt4_technical_report.md,0.3819
6,Como a recuperação de documentos externos pode...,recursive,retrieval_augmented_generation.md,0.3621,retrieval_augmented_generation.md,0.3532,gpt3_language_models.md,0.3251
7,Como a recuperação de documentos externos pode...,paragraph,retrieval_augmented_generation.md,0.3620,retrieval_augmented_generation.md,0.3592,escrita_academica_ia.md,0.3465
8,Como a recuperação de documentos externos pode...,markdown,retrieval_augmented_generation.md,0.3524,retrieval_augmented_generation.md,0.3308,retrieval_augmented_generation.md,0.3305

## Análise comparativa das estratégias de chunking

Foram realizadas três consultas semânticas relacionadas a diferentes temas presentes no corpus: mecanismos de atenção, alinhamento de modelos por aprendizado por reforço com feedback humano (RLHF) e recuperação aumentada por geração (RAG). Para cada consulta, foram comparadas as estratégias Recursive, Paragraph e Markdown, considerando os três chunks com maior similaridade semântica.

Os resultados demonstram que nenhuma estratégia apresentou desempenho superior em todos os cenários. Na consulta relacionada aos mecanismos de atenção, o documento *Attention Is All You Need* não ocupou a primeira posição em nenhuma estratégia, embora tenha sido recuperado entre os três primeiros resultados pelas estratégias Paragraph e Markdown.

Na consulta sobre RLHF e alinhamento de modelos, a estratégia Paragraph apresentou um resultado particularmente coerente, recuperando *InstructGPT* na primeira posição. As demais estratégias também recuperaram documentos diretamente relacionados ao tema, especialmente *InstructGPT* e o relatório técnico do GPT-4.

Para a consulta relacionada à recuperação de documentos externos, as três estratégias apresentaram comportamento consistente, recuperando *Retrieval-Augmented Generation* entre os resultados mais relevantes. Nesse caso, Recursive e Paragraph apresentaram scores de similaridade muito próximos na primeira posição.

Esses resultados indicam que o valor numérico da similaridade não deve ser interpretado isoladamente como medida absoluta da qualidade da recuperação. A relevância semântica do conteúdo recuperado também precisa ser considerada. Além disso, diferentes formas de segmentação modificam o contexto representado pelos embeddings e, consequentemente, a posição dos documentos nos resultados da busca.

De maneira geral, a estratégia Paragraph apresentou bons resultados em consultas específicas, enquanto Recursive demonstrou maior regularidade no tamanho dos chunks e resultados consistentes de recuperação. Markdown preservou melhor a estrutura documental, porém produziu segmentos maiores e exigiu subdivisão adicional em alguns documentos para respeitar os limites do modelo de embeddings.